# -*- coding: utf-8 -*-
# StreamScanner — Copyright (c) 2026 thaarfknight-star. All rights reserved.
# Source-available, NOT open-source: viewing permitted; copying, modification,
# redistribution or reuse prohibited without written permission. See LICENSE.
"""
StreamScanner | اسکنر سرور استریم
==================================
برنامه‌ای برای پیدا کردن بهترین سرور جهت استریم روی Kick.

قابلیت‌ها:
  - تست موازی همه سرورها (پینگ + اتصال TCP به پورت RTMP) با اینترنت خود شما
  - تشخیص خودکار نام و منطقه سرور از روی لینک RTMP
  - رتبه‌بندی سرورها و پیشنهاد بهترین سرور برای استریم روی Kick
  - افزودن / ویرایش / حذف سرور
  - درون‌ریزی گروهی آدرس‌ها
  - تم تیره / روشن / سیستمی + ۶ تم جدید (اعمال لحظه‌ای)
  - رابط کاملاً فارسی (راست‌به‌چپ)
  - بررسی خودکار آپدیت از گیت‌هاب؛ انتخاب بین فایل آپدیت (قابل‌حمل) و فایل نصبی
  - ذخیره خودکار سرورها و تنظیمات

اجرا از سورس:
    pip install PySide6
    python streamscanner.py
"""

import base64
import json
import os
import platform
import re
import socket
import subprocess
import sys
import tempfile
import threading
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass, field
from pathlib import Path
from string import Template
from urllib.parse import urlparse

from PySide6.QtCore import QObject, Qt, QThread, QTimer, Signal, Slot
from PySide6.QtGui import QColor, QFont, QFontDatabase, QIcon, QPixmap
from PySide6.QtWidgets import (
    QApplication, QCheckBox, QComboBox, QDialog, QDialogButtonBox, QFormLayout,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow, QMessageBox, QProgressBar,
    QProgressDialog, QPushButton, QTableWidget, QTableWidgetItem, QTextEdit,
    QVBoxLayout, QWidget, QHeaderView, QAbstractItemView,
)

# ----------------------------------------------------------------------------
# ثابت‌ها
# ----------------------------------------------------------------------------

__version__ = "1.0.3"
GITHUB_OWNER = "thaarfknight-star"
GITHUB_REPO = "StreamScanner"
UPDATE_API = f"https://api.github.com/repos/{GITHUB_OWNER}/{GITHUB_REPO}/releases/latest"

APP_NAME = "StreamScanner"


def _data_file():
    # در نسخه exe (PyInstaller onefile)، مسیر __file__ داخل پوشه موقت است و با
    # بسته شدن برنامه پاک می‌شود؛ پس تنظیمات را در LOCALAPPDATA نگه می‌داریم.
    if getattr(sys, "frozen", False):
        _base = Path(os.environ.get("LOCALAPPDATA", str(Path.home()))) / "StreamScanner"
        try:
            _base.mkdir(parents=True, exist_ok=True)
        except Exception:
            pass
        return _base / "servers.json"
    return Path(__file__).resolve().parent / "servers.json"


DATA_FILE = _data_file()
DEFAULT_RTMP_PORT = 1935

REGION_IRAN = "ir"
REGION_UNKNOWN = "unknown"
REGIONS = ["ir", "de", "fr", "nl", "uk", "tr", "ae", REGION_UNKNOWN]
# نگاشت نام‌های فارسی قدیم (servers.json نسخه‌های قبل) به کلید جدید
_REGION_FA2KEY = {"ایران": "ir", "آلمان": "de", "فرانسه": "fr", "هلند": "nl",
                  "انگلیس": "uk", "ترکیه": "tr", "امارات": "ae", "نامشخص": "unknown"}

# لیست سرورها خالی شروع می‌شود؛ کاربر از پنل مستراستریم وارد می‌کند.
DEFAULT_SERVERS = []


# ----------------------------------------------------------------------------
# رشته‌های فارسی رابط کاربری
# ----------------------------------------------------------------------------

STRINGS = {
    "subtitle": "بهترین سرور را برای استریم روی Kick پیدا کن",
    "settings": "تنظیمات",
    "theme_label": "تم برنامه:",
    "theme_dark": "تیره",
    "theme_light": "روشن",
    "theme_system": "سیستمی",
    "theme_midnight": "نیمه‌شب",
    "theme_emerald": "زمردی",
    "theme_sunset": "غروب",
    "theme_amethyst": "یاسی",
    "theme_ocean": "اقیانوسی",
    "theme_rose": "رز",
    "autocheck": "بررسی خودکار آپدیت هنگام اجرای برنامه",
    "current_version": "نسخه فعلی برنامه:",
    "version": "نسخه",
    "downloaded": "دانلود شد.",
    "check_update": "بررسی آپدیت",
    "checking": "در حال بررسی…",
    "save": "ذخیره",
    "cancel": "انصراف",
    "ok": "تأیید",
    "do_import": "وارد کردن",
    "later": "بعداً",
    "new_version": "نسخه جدید",
    "new_version_title": "نسخه جدید موجود است",
    "version_released": "منتشر شده است",
    "your_version": "نسخه شما:",
    "changes": "تغییرات:",
    "dl_update_file": "📥 دانلود فایل آپدیت",
    "dl_installer": "📥 دانلود فایل نصبی",
    "add_server": "افزودن سرور",
    "edit_server": "ویرایش سرور",
    "server_name": "نام سرور:",
    "rtmp_addr": "آدرس RTMP:",
    "region": "منطقه:",
    "note": "توضیح:",
    "optional_note": "توضیح اختیاری",
    "auto_hint": "نام و منطقه به‌صورت خودکار از روی لینک حدس زده می‌شوند؛\nمی‌توانید دستی هم تغییرشان دهید.",
    "ex_name": "مثلاً IR1",
    "import_title": "درون‌ریزی گروهی",
    "import_hint": "هر خط یک سرور، با قالب:\nنام سرور | rtmp://host:1935/live",
    "scan_all": "⚡ اسکن همه سرورها",
    "add": "＋ افزودن",
    "edit": "✎ ویرایش",
    "delete": "🗑 حذف",
    "bulk_import": "📥 درون‌ریزی گروهی",
    "col_server": "سرور",
    "col_region": "منطقه",
    "col_ping": "پینگ",
    "col_tcp": "اتصال TCP",
    "col_status": "وضعیت",
    "copy_best": "📋 کپی آدرس RTMP سرور پیشنهادی",
    "best_server_lbl": "بهترین سرور",
    "add_first": "اول چند سرور اضافه کنید.",
    "scan": "اسکن",
    "no_server": "هیچ سروری وصل نشد. اینترنت یا آدرس‌ها را بررسی کنید.",
    "copied": "کپی شد",
    "rtmp_copied": "آدرس RTMP کپی شد:",
    "copied_msg": "در Meld/OBS وارد کنید.",
    "select_first": "اول یک سرور را انتخاب کنید.",
    "select": "انتخاب",
    "delete_title": "حذف",
    "delete_q": "حذف شود؟",
    "import_n": "سرور اضافه شد.",
    "import_none": "سرور معتبری پیدا نشد.",
    "import": "درون‌ریزی",
    "failed": "ناموفق",
    "down": "قطع",
    "up": "✅ وصل",
    "down_emoji": "❌ قطع",
    "update": "آپدیت",
    "update_err": "خطا در بررسی آپدیت:",
    "update_avail": "موجود است.",
    "update_latest": "شما از آخرین نسخه استفاده می‌کنید. ✅",
    "file_not_found": "فایل موردنظر در این نسخه پیدا نشد.",
    "downloading": "در حال دانلود نسخه جدید…",
    "download_failed": "دانلود ناموفق بود:",
    "install_q": "نصب شود؟\n(برنامه بسته می‌شود)",
    "installer_file": "فایل نصب:",
    "portable_saved": "فایل آپدیت ذخیره شد در:",
    "dblclick_copied": "آدرس RTMP سرور کپی شد",
    "server_word": "سرور",
    "region_ir": "ایران",
    "region_de": "آلمان",
    "region_fr": "فرانسه",
    "region_nl": "هلند",
    "region_uk": "انگلیس",
    "region_tr": "ترکیه",
    "region_ae": "امارات",
    "region_unknown": "نامشخص",
}

def T(key):
    return STRINGS.get(key, key)


def region_name(key):
    return T("region_" + str(key))


# ----------------------------------------------------------------------------
# آیکون برنامه (PNG داخل کد، برای آیکون پنجره و تسک‌بار)
# ----------------------------------------------------------------------------

APP_ICON_B64 = "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAB5zUlEQVR4nO29ebgl11Uf+lu76px7b88ttSZLsjwg20jGBpshBkMbk8c8GlpxHhCHwfARhvAFPwj5EtqN4RFeQgbCEPwIhGfiBLVjIIFgDAQrTDZhsA0WxsaSLMkaWt3que+951Tt9f7YQ+3atXfVrjp17j0t99LXuuec2rX32sNa67fWnggdxMwZgCmA/PTp0zhy5MgcQAGg7HoXAPnZAcA9J+8Rp37yFN13330SgDQPMxAKlvT2d77zht/8w9++7amL55//sbNP3Vpsb99+pZjdOJvPb9yazQ7sWVu/+dLm5rrI6Ibt+SzbnM0wLwuUZQnJbIoBMetPA4ioXgOiWnUIALOsahWsaSxvACSctF5iZoAAYgKDdXqq8vXTu/nWP3h86LxANj/iJrMcyt9kyd53AAQCm/z0dwkGWDbagQCVlgjCazQpS50gUHZLe5LOj5w2Yj0OmFmVsshYUIXYOuciQ56pfxvTNWSUXRLA03v37NnanM0ePbCx93wGfnRjY+/jRw4ffuTQgQMPf8ZLP+Vj3/VVr3tsLZ9szsvC5UW8/Ftenj3v7PPkyZMnZXtNm8TMZmBOT58+PTly5IhEJZszIpLxt5vDNlYAiPRQYSbzOeU9U87JkyfpnpP3ACcVcwRgbTLFT/zCTz3rV//sj17y5OlTLzt34eInXZlvf8JmMbt9Np8fnks5LRhgLlBKWQ1+KVUOrP8aYbIlclwo3YGra8HkPXdrZwUG9ZdNGW39FRAWL2Pnqyu07CSRDoMJ5CmqBkMcahj9bCGK5Nloy1jaAB9++4UUg/uFtDKyCqy9TsQtTeuWHRxL+oHtK/09ywAwBAmQEMhJIM8yTEV2YWO6/uja2tqHjuw/+P7rDx3+k1d94ie/743f8b0Pb81nVb5Hj+Z41askTpxoFVzLhiNnroy639uImHkCoEhJPIiOHxc4cQLQlp6ZxTe88Xv+1l9+9ENf+OS5s6++dHnzk7Z4dmBWFiglA6V0LZw258yuBBKIdK8Y5Q5r3fwBFxs07HzsIV9LJasEnMHVOkrb8tDkKikSqCnHLgXWiyI8Kqg0UhkrREzViFTV062pIQfrVlafK7CTZxAiw1qWY11MruxbX3/fkQOHfutFt97xW2/95z/5R0RkrLfAsWOEkydTkPawKjDnxMw5gHIMBVBDB8eOZdCQZkIZvu8n/+8XvvOP/+C1j54+9ZoLm1decqWYQ8o5UDIASBBJJdmCABArAYiP/BRuOxRA47eVoJi5S33duBYhhOK4NaMKPyLIw0CsZ5gC6KpOYzwRyOJX45tAgCAgCCLPsUfk2L+25wO3HrnxVz77pZ/2Sz/1vT/4F9tloV4+dkwsQxEwsyDt4zMAdPkLKXT8+HFx4sQJAlBuTNfwNW/45i94z4f+8ltOnT/7xZeK2XpRzIESDFBJSj8K9puMqHvQxB53CXNI8Fuh+lVErhDywl05vOwaJbhKq0htYyLV+HQlIWIwpFYKGYgom+TYN1krbj505B0vfvbz/t2v/9v/+E7tImTH7r0XJ++5ZzRFwMxkEYBlaDgRjkHgJMr1yRTH/q/Xf8Hvf+C93/vUxXOvvjTbBiQDoIIIggFlpsYSvJhb+/FGRgh3Wvj98n0azM+CaGgR6hqbXYHfvuORBAiQzCzBnCMT2Dtdx00HrnvXy1/wif/yv/3Yz/76djEHjiHDSfQOFoaImYUNRS8i/MePHxcAmE6i/N5/9YN3P+crX/m2t7/nvnc8eOaJV1/a2pYkSbkYhNwK/5h0TfgVLQy12wKIi2Q7JE89UzHo3RGooylS4rq9iCWYpQAhhyAGo7y8eUU+cPqxV/2PP/n9X7vjK1/5377jR/7pS0kF0VnL3MJEzJw5gYfedPT48fy+EycKZs5f+c1f8/0f+NgD33fuyqW9KFmCMgY4i1qAoTD+Gq0mhRCAMy07KK/dQjNDaSxUW7VlCSkJeSYO79m3eefNt//oe37+l/85EW3j6NEc991XDGbViQFIVWZvFJABKL//3/zwi3/pvnf89CPnn3rlfHsOUFaqZ9y0SiP5T7W8rnaFsbIByb4UsNhDFQCQFgt6JhPVjHwJ5myyPsWz9l/3v7/sZZ/5+p/4gR99H44ix30YpASMC0BExH2EX88zZhmo/MLvfN3X/r+/+ct/+MDpJ1853y4KokwFNFTCen36RO5Txs2SEGsSjTkuCbtbl9HI77QFhB/YHeFfJX1Tr39GQvB8a1Z89MyTn/bWP/zt3//87/p73zD9vbwAIIa6BAKA4LbptgZTICKinET5ya/78jf+3gff+4unz5/bD0YJErmK6AcsPxLbNiVRKA25PiMtvyOvemFdEjEr2M7y49t6j0K6Lc1CA2YCUU6M8umL5/f9wV+97+de/HVf+KPMzPfffz+lKoHa4iFmFqnTf3qeH8yMl33Dl/3MXz7y4Ovnm9slCeFM5YWF3zxKopSpPHeOn+DDJbVa8JqQriD5qypbxstu0CrPKDkxFgKYS1lONqb5C2++7b/8xX/6za8novI4H6cT1L6K0KzXYWYSSK2usvyCmelTv/HL3/KBxx58/Xxzu4Ar/BzpTIMEhzRsCFUG8/EShRYBXaNEWqJP4gcKhwj/gp5FUv6rSFwhAgaIMpHPt2bF/Y9/9LUvPPbqtzNzfoJOdCIBx92n1FkAAiAmIi8/5XVf/B///JEPv26+OZ+DxMThLi78bi6uAPvCzF66lHfc34xlMXyssjZfWfICeYsE8WL5mz9DFwgFXUA0x9ozmWqLvrgQU5E//8gtb/vQvb/7WiLC8ePH+UTHfgJmztIQwNGjWUai/KSv+4Ifeu/DH37d/Mq8sMLf5u/VBBPNjvNLdtOazy7c9z/7ZenFltH8r1E3NdosQUB7ybDuqFTFEhP2WLpnRDA1gSwaAECUy7mcP3Dm1Ne8/O992c+tT6blrz3+eJaSjd0MpPIJxOmPHs3pvvuKo996z7f+7wf/+t9fvny5IBKZCiQs6OsD/af8hrx7jdKJPI29Sv65S21sfVyNCwexSS4ma9P805/7if/sj37uv/6QPPo5resEzDRgFP4fO3Ysw333Fd9w4g2veO9DH/53ly9dLpXwyx0Is1+jXSGLolZY+K+RQxWSIkHZfHu7fP8jf/Omv/OPv/OLcd99xbFjx6JIgIhkfCnw8ePi5MmT/Hu/93uHf/NP/+gt565cnpAgUsLfQakaOCXdtdWCO0xXsfB/vMB/n7Q7wACREHTxyiX+n+979394y1vectvJkyclAkFBZiZ3L0BzLcD991MuMvltP/GDP/nY+TPPh0TBzGmLDVLHTl9XYbQO3sU15tdoHHrGdN+IWkspAUEk5JOXzt38I//9//v3zAzcf3+jAL34T5qVgLXzAI6pvfzlF3zn1x974MwTf5fnRUHgPJmRvnVKiQe5aRZqr2vC/4ykWHB4WcQJ/7qInFjLuKxlkLL4yOnHvuSr3/AtX4eTJ0tEXAGzHZjtVKBabUTv/h/v3vcV/+673v/khaefrdb+sOgteWMEA0OLfhai5TT6NdoF8sdE6PuydH2SgHc9T9zrUDNY3BEAVdaXAMks6eaDRz72p//qP37KrS960dNgdTKia+xNEJCtC3DPPYIA+e1vfdP3nN66eAcxlczoL/xB5hZ8d5TO3EkzcY2WRrFZoasJ3HUKv7O0PdUH1nkyIACSp66cv+3Lf+T7/lEGkrjnmFBJKnffrANgIlJ7jE+elD/4s//ijgdPP/GPyu1CgpA0nxjjP8ivP9+vOY7m4VOfGMM1WX/mUpc8xMbOGGOiSx7HUETBA1YoIW89K0Ak5GwuP/L4o9/xz9/8M8/FyZPynnvuqcXxzBcCgBP3308E8L3v/O03nNu6vA8EyWMcmekLud8JKah8SKddbRbhGUEE9FhhvkgxC7+7ysuJo3GqDhcAcFEAgYQ8v3Vp/1t+521vECA+iZMNF0CJo7b+P/DT//o5j5x76u/LWcGEBax/X+qrzYc28DVUsGTSU4h9BXSn+sVfVTpWnim/jUHJbWRQADIuCn7k7Omv/39+7idux0lId69AparfdUIQwL/+x//zmy4WW/tAVA7oxnam3dxSrfNurQAkXJstGExX6TqCRWiRNS21fNpmqXpoSb0xT6OA8sJ8a/9//t13fpMA8Yl3vaumAJiIgPtQPPbe9+796BOPf325PQMR+Re37C7F3Ia+7yYrnsQI7TUah3bSXVtp19ANLrAV5OhO25QciUQ5n+NjTz/5jSXLfXp5MAE6BnDsmIoO/r2f/bEvvjDbugMMyYAYTQCc+tjvqVmPAf2HdPhuHki5m3RN5w0nP7Adex5930tgN0wt5h8xICBZnt28dPtXfM+3fhEAQMs86cMBKCchn/Oaz/7Vv3nq8S+DhAQQP8yzZ+mWFpGn0dYBdFDtYJFnMpR1ImF929ZvklXRk42zBq6iA0VjF6ssNP4qI0ZAycTiBdc/61ce+rU/eM2sKAQAKd6INxIA+UM/869vO33xwueikESN43VWgHYFtq3KyB6Z3OPTnskoZ+y6LTVQuaR+qBSIgGQ6c+n85/2HX/r526AvnRS/9q1q3/Cv/8nvf96VYrYfjFJN/Y1cUzf6utLEkc/PVDKKoN8r9u+O6I9+i2CuPlpiI+rVhgwQGOXFcn7gF37rNz4XAHD0VZn407/+a85AeOrsmS+aFQWrSwlGOtBx1WUptC5hgWDLrtGilnzVkUAfxGL6Ty7hUNKlNVGIzzHGoZmS1YyT4FlZ8CNnTv3tDADuu48F7ruvKFhuPH3p0t+ClES0hJt7VoncmAo5f/0gZf3DLpNeXBP0zBzruJOe2641jWmLEabKBhY/mFrZ8gJ+bcLfq3pVYiIISElPX7zwyoJ5HUApAOCb3vSPX7Q5n90GycxjXt1FkX+rQrFglkUBq4wEIhZxlS35YBrQD4s2w1jd709BR9P1mO7rvcjKHiQqIJk351vPef2b3nA3oIX9wY999FO35NzeEBTPCKstEz7FFhG5iig6zTiSKzBKmzkZmGhx9DbeISN/xTvVPf9up8ht3lVtnj5jyxg0IrnFpfjgQw+9DAByAcLpc0+/bF4WABH3m6S/RlEac6kp4Cgj7rDyCX1n0c1V1tcssfpS6dEqATIGAOKyLHHmwrmXEgBRsqQLm1fuhlQH/wOID7AhEL5LSy0LVcQEMAbJfJlwjW4Xf+z9dWk0S+IwFUUmfRvzKhGiGu0ADPXX3uymEIeq6/LVa/aGAAKxlLi4vXm3ZCZx/uHzh65sb92mBxW1+iCpbZ8MS1AXjjH71hVkP/DnC2RotsJdT+LzGCoLXpq2GFUfivLY0kfXaDGKjZFUQ9D3vVhesXG0yIQPQJCM2Xz7+ecfeeSw+NFf+clbtovtm8GM1qO+U8gVnpjWWiTvMQd3n87caUoabIx6yGakmMVu0KqyPQS5jQHCYopkBGJAAIzN7dmNb3jzv7olv/+hB54zk+WGcRBa3x4DCrXBmVWnFB4713vrvykxAj9NEMFcRctd22ismMnY48mdKu4qM/T7UD6WGuognrNce+LSueflT154+vZSaS2J1DUAMab8ufQQxI+911VWSBBSO9t/1+c39HxIx/UR/hCZEGxoZiIWzzD5htKMKVTLyhuou2uraAja2n4Rio1jt7wUBZRcHpv4Hkswnb18/lmi3J49v5QFEkJdFdMpz/x0KRXoUix+/l1BkLaZMrdhY4GW1Lr2pRa+gu6971L5QaA23sdwnQK8ji6nY60RGRJ0HTv+5Oed8rxrHI9BVT5cMuPKhe07xGYxv1lK3hnN62q4mLaLvWPIF4S+nRbTrn1nxEbrFDOn7+Xb5hvG2iklSDkS9T4oblkC1lZeCvoEqv5fhgzs5qxlyGgCUHFAiW3MbxVbxfxGFTxa8hKy3Qq6xaz7qlCfvQexHtoJ6zEGLZOXrmDaKtJoiieSUUP5sPmdmBmzsrwpv7x5eUNZjx1orRQlsOwBG4qqruJA6YqLtKGlVarPblk+l3ZTCe5E/Y3t7rla8uKlyxviwMa+WyHnIOpopqEQLsWX7oLhKf5+LG/0fC/mcvh+4jI7touHWPltwaTdpr4u1pD83c/LgvTAailYALWl0v4YCQIDIpQlDu7Z86z8ytaVHJxpp66lZl3WJTQDEGW45Zn/3O9EP+8u+OtHl2MzAn1+iwmh20ZjDb6UwbbogExtz65yh6AWN59VUlg+jRn1Hz2fFuaCZarZgM3trSyflfLAwgwtanG64KyvfLoGWluaZboZYwlrCpQPKcY+ZbSlTQkkdgl/jAe/f0L9dTUohKG0yPhLnTFwjV4NYVOVDRE2Z7NccIbD6sWOIGAblB8LEvVBDX2ELTQ4Vw3GDaFVq8eq8XON6qTjfAQiSInJ2vTGfGs2Q/3+sUAPxrQ2vN8Xpdi0TWhKJ+RydM0Bt0H2ZdOiVjmUJmY1Y+ipbfqwq+w+yMX9HMq7D6JbhFLqn5pPKg1FYqk8pNQhsc6FLNfyeTlXq4P1oQGdmXb9ZgoeSiHhbkvXxUuInxQINZTGGMyhPEJ+epvvntqOY9Ai05Bd46qv4IYUYQofXTTELdttivDDJgYw20Y+m5s7AnoKPxAfgG3ZxbRTKIDYV5uGBD2Ubwg5pJbRl/rmGWvrlMBqDBX1LbuvtXd5iD3bKRo7+BoDxl3KdUy3eBntSYSt2QyiLMud89tSNXLMKrj/+pTl5xGiEKLoU15bngnvk/1fDxrCWwySx+oeK3enKKmvF2TIdTlTlZ/bt8uWnx7jqPFelAhFWSDvxUD1bjf8DJfZjQxi31PIt2Btfq/7fKyYxrIFIwUdjOHzDqUhCmyUQheAcLH4R2g8PhMCnN5ioXyQj2XSp8LV1P5p81tjQb1Uix567vPXRn3G2ADr0JmsL7yO8dvXLw4p9z5jZhGXJLkAUiiA3QJ78uZk1ZrWTbeT8ZXUtkuJnZnnTMgbA6XLL/eZiRXYt8O7rLaTMWm8zO5e+KGDckxKiXjHqIUXYoQ338QgfIif0LNFUVZfBbIUQaH6x1T5DymmtjHbEl8h1o8WACKd1NV2fpmdxlZlmLe+2FahkJVzGsj+PCQQFXmHaifhDghaes+jguXTIpZrhMHAfpuE+EkduAh8vtqIIhXp09axtmxrl1ixpo2HBk9HIHL5sD84Cbx6GiMq7PqfFKHxLU2LJe017mMKxv2HeN1iPHQWG4XJhM7A0pgdOcRypASGlinwo9afYC8+SQrohQbjyDwtQm2u8ZKIQ30dMhJeopxDlqML3vuZxqz2kAonCAFr7dXw+VKCebH8rUCJZuJVGFhDkcoy4OjYvjz7pqqNWgoeUtdUJJWSz24EXl2KocSWdskBridIsRoheOEX6j8LwVg/WyI9FtjCfXZv6GEGizbGWsqOlNlK+mLF+m8D8wrm3/HdpRBUDcUAlhl0W2rQq82l64I6QPgmp47OGjOYF3CDhysTEalP13sI1yWE2jVz9TMA+/rqtS/6n8+323etjR3u5JqLYix/iHxh8GFQG0IJFs2V8If6YZHBkjCeXTZqn916hPJpq28ovz7Uh++dpJiwdLlysXYc0kahYoYg4rHudwyNG/cn/V3Z09TroYNtLEBE9l9v5nTjE7i2HJldyxt0+gOU6g+3/W72VkvuLyBj0TLLHUuAhwjJUtwRPWba8h66UKhvvcZ0ebvQYIz6hFDALgLoKbyMNIF3tU/LoLFfnSxZ3VUQfadGMVZCZbZZMmY0zkZJjSWkWsi+0Wo/fVsco00wFxXAAah0HIqhvtggCrxPAk142ELcUu5QSu03S11uT0uefjY+IoaSLWF+pZTMhvi/KRC8hUl7WLF5XkMGHQ1k33HKj0G92nfSyEaEoVTI1UyJnSz7eQofbh1SkZWfn/tun3zGdh/sUVhIG5vGJWhzDaj6QCmxB6DZ5l2vuGPI1UmpSCVlfCTwQETITcrWdosgLGa2KIBD55ENDMIF5+dtJ7OC536+scEeUgJ+oMZ/jbneF77yaNPk9ZpUi5Zi57WlBIp8nrsoJpB+nVxkRn7CDusaasOUuvjvNngUVSJOyZiqcVETxFQtGq6nDT3pFYaceGp+ErWgz4aRW4Ra2xlgMHIV6NajIYa0Qj/qjg8O7JDw9mA2ujinDdKGhNv93VUCbXzpwcSN35rpK+XHKnsvXd1F0gy0oaA26ms9+6IIy6v7V1eEA8LF5h2/UZzPsYHcWbb+7FjjKEUFPcVye2kY1trVZp/GQi4kUFdsAeoj/CPwlfNY2iZEQ1yG1Ix9WNIGfTXcsUqrhSkiocQ/0i6ECj6q7DQKIqrkwaKFihEyPmVnp8WgjPuVUN3jkpA+VkbN2kTMROhRTe4JCCydCGfZBUv6PIuk7T3mqnFhrKJCmAsOWtcgNdCVm2jJ1NGE1W7ANiWLAKtDfcdQPik+S1vhIVfAl5naQO/SwM5zQTVlQELY7Nkkl4xaNLp20YrDVCpErjOExqCx1jeBQmsZYlmnshDKu7p2KpF8TeEW0tFHo5JXVi6ATCgl2/OY7ShZZSBRW+3I9n/D8wXCiDvxtzyYQYjahDgEvX0mQ3mllu3n4SPGNv+0kUfc1QHgrDKsrDVpJcDMkEUJSKk6URCyqUC+NsVkfYp8LYPIBfKJgMgyhfiECSjqfAlgKSF1HEPFmQiCCASyisr+perKRraKpQSQqXyFAysZkFzqGEYGIQRAgJQMlqUuT2tbfQ4864tJmAAiBlhYiE/EDYBAqOIaRATJOm+u2o7cfnHeM6iIIPUMD6F2uSkB+vJa/UVWv4Hr7qauIxHpdTME5rJeFun6SVPn0jKk0gi9+EyCJSAygbOPnsWVM5dBWdYqmp37SHxdFhLANuVs6+nll0KuPPpG0csnj+pa1yePFeKmTXK56liRfd8y+iLCDeEbdV8xhPjVnUEkVAcaofIgO4QaJCwZPC8BZuQbU+y7fj/2HdmHjcMbyPdOMNmTIV/PkU0napySUhgEAgs9oah9A2HRJdfZdS5lkDYQpNkVgGAzaD30D4AF2XYk1krCyddUur6sQgmpJEAwAC2QSu9lEM7gNkrJjYoYlweoFBWxg7Jig8rqAFKPLa8STGTHh2DY8ghkXbaqDmwzIxKqcOmiPCA4ThrsVMpKlozJ+hTlb38QV05dBPKsHSgOGP+9iSOfQ+PcdTnannm85kkAZEjlfEYakLxHPlZAO9IkU926NwAGEbiU4PkcYmOCw88+gkPPPoj9Nx3E+oENUE4ouYQslTVnlihlCS7ZsXQ6H5ev0hGQxDowKoF3F2xFwU9s3QS5H6mK43kJ1SXRdardHcl1PoyxJkexRSmmsFEt/fZYrdVBukpI/z9aYh/3BhZAKYRnC0mw0ClUE0btBphC++TRCkm87yGD6CsBQsuJQH2FvpcQGi4S31tYw3qqkSqhr7WpmfLZnmGyZ4obX3wbjrzwJmwc3kBJABcSs3IOFICCrqSFyVijOpPudwYrV6KNxdjP3jOmag13TBG05QnNr+BmwtArwl0OoRMIt24GYTPpuEjU5EZ4ozoK0vrF7AsxyYXLp0UgPeseS8es1wo5KHXsALkdxxKDBnRftNzFi6CAAugStsAzA02DFsc1SBpuBvPpQAzBtDUGwrzVTZX6TjptjV0icCFBYNx098246SW3Y+3QOmRZYDabmzedfSnda7ZdQSDvt+Rl06EasToKRbgQP9FaWfb7jO2Aw+uuARljitzNTxih9uqzSJulMUEgyhCc3ux8F+ky7Si2sfJvdFHIBXKRNAOQrBVAA0d6CX2hbFikQDoXutd8t0hFXHhi02ir4ELLULv5/k+tjGbl2LfUgsDbc6zvn+K5r3w+DtxxPcqiQLE167fHIYFU0Gkcy1JCOh6ysaBj8FrhI4aC3n7etsm1IhXaBTABTUDH3qImOlyqY5Cjz+xvXS5HH2KDMSR63dhcy8P77jPc1jUh2WrIT8vrMRcgIrOGGgjAbMl1bEvwRT/vrqsFLVexRrCZNQeytQZtDRJSAiE/yAtrExF4u8DBWw7i+a++E9m+CebbM2Xt2yC7U5wfmOuikEKxQbc++Ti9btcZdFBNyELJJbS4l9a9oUi4W3IV87C620wH2nbXrZQyiDsEWprsTFlwZjJGIYZkCTX9l/V7NUHYBrK0+LstBjcQA3CmcUJcmA7g8Ge/gBrsSCVHCalsRvTFnAg2EYFnBQ7ffgh3/u0XQeaMcrusCb4VVmee2xcgg1LiZer05qsJfwQ7xm3UpAolptNpqSq3WQLXfmXND2sBDiJjUxc7A0CBeg2A1AFqgLxxsnVydsd5mktlX3f/LkJ9XInY+y4vHPldU8CR9RrCz7ir4AXJ9ilV8NI+iLxhNu6QmYcz/LT5TETgeYm9N+zDCz7vReCMIQsZtPqk09eEh+ptmnK1YgoR2dnEXuOgbU7aggOdcaSHVfnu04T2b66aZJu89sqYVnFUUp2qRo8zI9QXVSw6/sdUIj6F0KHmt7ESsApS6c5tQOgmo67Q1gpIgUUBi2JdCrQMbJ13LPIej0Tr55KRTwXufNWdwJqAnBXBvGouGdebwf0u20aAo4xciO/DfQW36/UAOHksti9MSRlZKgimipM1pKQ4Uf9vdVPYsypaaZKG63IQXCcI0jEFr6yFiZ0+ZrJrLnrTGILblkeorjFo33inwtK+YWwiAJ02CrsDpokDvwVdgJDpIQTzrKfxHjqKxRd05mpRSzw7AmYFnv3yZ2P9yB6UswJCqOCVoOpwE59t919tMU6gWvYZdQimR+4gV++GXzb5duffxl2ofL36jhw0pUl1U3tlzHNTD2J3ujGOlGJDwIythvCPTgwQ9+qrladKs6Ex+6b/pt0MFMqbnYHnWvvQbyGmInGDOqT0YYeXD7vPvOh6LX+qLLD2+w/dfgg33nUTiu15DfabYGZqhLkL4PQJ6rF/GEmtfpF8lf9RKUQnfQ1tIFURxRMRWpCVIVEt7nXLa2sHH2mplwHpngXhv8MJvKQQsVq/oH26ql0p4gaQaYie5ViIvQCziRSSxwgNVgAtY3Mc8s1sW9KkAxQNjFULcm5/2bNBOQHb6hG7m1l2opMi1Hdqq64wPDREsBF8k6+B4jX/HtWYZqj9TzYPOGq4gzHXuNSSuno5pW3JQQS+WwbtRozWRTWVGYtgOAy0GCUnHzd/Z/FI/f1ljLOeWQ5WADXyYIX93IYIWiG/8zmmxbryZuf3mvWf4dCzD2PvLQcw256p1WVmPDFHDz8Zi9yFQH2nD2P5xXhuxBi01jaKoK472MZf4PAIJFp+6OaW4XTcsv6hdrAM6YVAATeOdB3GPJsDgN5/xJDUXAYdpbaTey166FASdoo0TSn2lp2EylQKoC1zX9hCz/13Y9A/pYUToEtQ4D0e1YYfLzNJOPK8GyABMOsNQQ6zO2b7m+N7EIW8rKTiW6wou2l65s+Bz+4ux06S1YVvJsgqqfocysZFQQz22rVqoQigB0FtKBJC7Q4cvBDI5uiVFoxJOQJBhKStx0MGTEwONbUjgA6NQ2S2aUYaK1Vrhd4Lffb5anvHKAFnsp4LifVDe3Dw1utQzks9MFsy7Sld7eC9rgHN3HqzrNRCSS9pIJCsgldKrrvf71qRaBBCBf8juTbYrQuAEMpSWlAWQwFOOYY/890FdGobo4LVVYyBazMy7j4BsiqBa3kbbKOUilSBCwkFPzyjEKVQnCA222LSufIQTYsmuh1CMeF3fk86ECRE1dbeyID181ukIn4+KdSYOSCgVMG/ycE1zLfmlbMr6najNpD0Kid3+Fs/kQET8iIhkJlNQXZ4GWMSsigeXGJURxC4vDvtVltApC24EATKlBVhmCnDmshUYy4g9CorlZ503sSwbUNebtZVcNFrbS7JtI5ezEUmb/K4qfPDup3tqLLtqJ+707tCqHMWnEoI1j2h3Rwr4FpfMDOEbd+qjcwKSmIgz7P+y76DwcKuQUoVKogp4RR56ULtbe9oakcAbs83Cmmx/DtAUQtmOtTbrWYEa8+eDZRPz9Qe/9qQdAYuOVnpT0bhEaAO9NDtkk1ygBjzrS1sbW5hvj3HfLNAcXmGcjZHUUjIUtqtwFZ5AFai3dMByHlc7+AmNLWrbgU5Q96cWBQ7hNSxRFQJKAxMrzGgi3cExiozInUwilER5iw9KH6ISS2rDUX4bb7qMA7rIrjC59uVwJJi9+APy5+5z0G3CxGp7cz19e2NNlZLv4ErZ68AeTZ8bCedImT6IAVlDGOjrViXuk8E8p9Zzc/NND6k9Z+NgQLaEHJIH1ClaGmSY1IQth++6HVwmyolALJCPKwGPmeAgMDTZ5/CmVPncPniFor5vLpQxNXuQbgXagxtTts0Omuhc9fbN8BFyCoNpGB7G0FkBG+yCQa3qJlXROFExxMHPrc9t9OjKW2h+c1EhQyDw8LTHkPbOdT15vdUGemS24Ci87/3mwVoNLD3extji8AZK3yVdm1oaBcqh7KWEpP1KaYbUyAjkLFeoQFoizW/u3vEAUKOsizw8N88gqefOq8GWpYBk0y7jxwepClUUxQcyMNxvaJwNVRwVwfI7tfa6mOnurSm77uihtpGft+GjGjQlJmMUHC0NtbZ+XEAjWnRh1AvFyDyEoCmxl2UQgMtaDlb3nfRLXnPwJhMc1BGYClhgWmkbmSth08MAuOhDz6KC2fOgaZTwLgj7LhFQw1wskUxozJ1sLcou7Ypq2R2LOxJfCFQTuik46Q1Hj71cYpbXjcAjgTseYTUM6++ZS4rz0iT9EMAC/TvjpLpJDuPrQJSWaYPgWypRG2Hn/+MGZNJjicfOY0LZy+C1tbVwFhU6IdSL+FwLJuPMlLySFL2izSAcZ0o0Y9OyWvBbGq0Q4O/EwGOS3kQL1v/3VhJbjam70KP2di1Ngi3QCMIWBugXLl+Th2EcBOHGXbd9+ZEAmE+K3HqiXNA7lgFYIRBu1Nk0EHMf+t+3dIyrNYuBpZV+YGfjKJdSn3h5Uv1Z0vWAPFzraxPRvVD4Xz/39CYfPrKxUSeTT/ojSrVXv2K1bb81JZhRP3TWvTfS6KmkQQuXbiM7a1N+Cccrwwlg4Ke0LorOEUiHBAcSn2n41xy3fQ+XeMrN2sIua4vl9LdFGi/5Y+rPC7MJpgT4act8LdIbKAr3uA7NjGfzA8qsVEYVVpGPFYlmfVZ/fU8Ny9tqWP5XTSx21ZrNyjWtySGoyG/zwwU66LQGCazioCbad383fdjKH+Z3WvjXKnR1nGLblfZMWFM+S32fjSNL7Dw3BHzj1Gb465NJenIuLfhwkdYdklKh4JqzgUz5ttz56tcPeEfiOx75d8QNtH8PgpcHpCJhm/Uaz4N9fHWGjyz26nGocC268WWIncWCIM2mGIKoNHBgd/H9of65OciFPIFX/9zXQcHt9UPt+guxj3AgggopbkCbMUEf9co1nED3IFQULPNrfCNBAcetiHVQVS/JGUxSpitqH0dSeicQGsjCGhRUMznj7kMbroud8D9zf6u4LxaUMbt5cGBdsEB4gwkqtKqnWRq1Zw5e76LjB6pMezGJMzP8bhidwFu9otGmxdxv3qRi7RiSZwdc6lbrWsLzML5R6/lcgavHcNjtUMACcRd55T8IorN7O6Moay2MpL7nu2fxjRg7XRfX2hdPymEBroK9vN1+9otP5TWJVteQu86Zdidf/4OwQ6SYGvPhAh0XF95DSpA1BHMKqOM1kU7HWmtIvDiBLX+9iyKt7KRQ+MtCb5Hfu/SuQ0fMpIxIa3PWsctqR2sjfHP3t8uPr3ktbaqjGNzNEchVb2gmtvtF+YzRR4PNaSnIbmdS+c4yvA/9xEQa7V7+oYujwDEREe7zVJc999QUgv6vUwGZpjKS90zij+v5e26WSNTI1vTX+7SZ0/42vjvoti7i+rcrpmQvu3njvW+BiGkFGsW0Sw8b8DQAHm/N+Qxgbew7LE9g6/p/zWSNsuJNoqvdZzyQj+3kBtTnE4n3o89KdApBIQPuQgFiPy8EgxD9J0+VEMnC9IgZOOUT1T/yeYb+dwov+N7KxsJ9fcVlf3d/i8hjx489SU7BshsqqTFtKmhVKaD6ZpXUXe+H+WXml/1T1Lf/NLvAg5zYo3E2voUEGLYbrHIwGNplhAn5jm2Z9ApOCMKPstYIT3yWKCdDPpts8Rt6Cipn2J5J0KzMWQxVpwXYsnJfGIdOgnCBjRgefBQ0C5+gsENp1yXaT9oFMs/ukqx6UqojwLmBlzDD3H7qbPS8ZXWN6YQmVBbXVOoUS/vd/vcbYMAM6E2bvMYQnPL3pbY1kNBanmPYY4WGNW1ZZlOv3a1bYSM0bObFu1BCyaTBPjA6G6XPgujmMNjOSbEofpH8/bSOenVlW6EcGDFZcJ3Adp89BgfhumQkmmM1z6angP/mjwrkjW8nYQEWE0HFiVjsjbBxsZUn0qTxl5VWFsZBoX5bhA16zJIHgl2tZ6OYbDzKJr3KMKPgbJfHxTk5uOPoTaF0FVEsACnHPfzYD3W9RJXdQh5WyH0aNLEsnbbw83bPCZ/n+tu0hB/NkYtyI4Slz6ESLIEMsL+Q/sAqQ8J6YKSMTTllk3mLgLRPJFmIX+5I4lrzWygzb2XaCToD8T94lAaw4cX+Etyu7rcGYM4wfa/dp7QVCyG12QyxqzN/aFa8sWUDTXb20UNDJhrovTxMZEru9vIZSwRejXSJiCtwRRBMmqbb/Ohu9w7miWprcQHr98PyrPq+K3ex0iFf2Z2TtxxG2jMAJzPBIV+CwygMcvsTBNJl9oEbGB+vAiODcCuMgjp7eIiUs1Xp0KPZR1zBYJKTleiTS71M30TkqcpUmmohgpBNB/O+bzUrAM134nxZL9rFcjVSXNDboGRpcTG3g3sP7gXKMvKYoci9p0DSbPErHcWulrIdGKg3mPT2LqltSwRrkfS9FhLv3u/c4pG7yrKhc12HHXxycqg2mBnSEAiiscvu00Z+Olb2Kml8RRY8zyAWsYGLntarA3SpgYmupi2fU3h67EIyg83n0M+kQ+1AYCkGhyCVLUomLQ6TSpQMBPhhluvx8Wzl+pvuqfi9IHufvXaBN3vk2DaxJE/5u69XrSAMgucDgVrxFxUw47i96htjLbIq505MKIQfL+r3yOSvYghDfFgUUAgpuG8F14IBHgdRFXDuwLWpokXIccKxu7Gq6wj4kEy9zcGQAQWApIITAIsMrDIIEmo70SQ5h/cgFn1j0lgLkvsu24fDt98GDyXAb+9R10XCiiZwUjev5QseiqpPrRw3gY6owVlktPvoXqb8eGFuRp5VWURqNrm7SHS1mlDANUUZwdFx3OkvRaWJX+jVv3r8JuBWuFJBJuPPeC8JaIhZsgOEEVqAlCAmSpPQn+wIZGA4nSLFKT6+tbn3IwrF69g68o2KMs0jK+sW0P5hoBMyEBZQ1adF8yo1yP0tfmjb+qqnZGVYm1m0m0YQzAwlAE1f/IS1oNwmj8WaFuubW4b1h5djUPj+9fajTL1zO8P01/2u/tmNT7scetOWQQz9hZAelXJ6Xl0lhEaZPEt2ukKIHQKcKOgtgQudAg9DkC7Ln/CXSNQ6yAHhnsrDAkCJJTV9iPA1nNwirOpHKXAWvFkazme/cLb8JG/fAillKDMWyDE5l2y7r012F4VXM6tH+sM5jqj1C7n9dxq31OGWneaAOKhlufRPBuOl4PaqfqFK4VFFBsN5jj0Kk8/d/Y+CBZ19cMAuR2iLyAhCDDJ2tisbVhLpkXNeVf2LSjFVQKVPeiIAfQqPCVNymERvlW3DpjznQD/3HtrNVUjVO4xqXPzhUAJBguptvgSg4mj0X82MQIttsQEqVZNKKRAQCHn2Di4hufcdTse+quHUZYlRC7U2fRONQhsR26ldiLWzSwG0S6LW2uTF2n4y8RgNtbKaCizE85tt7p19DUGmzz9Nvd+sTk5r8e7vaGVvZz9K7zcXx1+7dUDrJW2URMeumAG9BVfpj71o+vrpRGbeQABko5As9NKjGqYtcGiZJmJGbIO45hK0ZiQKd6VLWUg4wigtmqsgzl/XKGFER+225HFVZlufgw1sN1LJ2srtwL5A/ZSCIZu30xgPp+jYAmQGlVCm3UXOLAROoIWLgGBEuaKKuMjMgBBAhLA/hv24fnT5+ChDz6K2dYMNMmtxbeMdnVOBDVxI4nQion1YDXvSYuiyG0bd8GPhRa+5LqQxIE6AQttLHINqpDznsXKbh5ks66tOHMgPOkE5Cp3BpA5Q9FBRu7FpaaeWivCslhb3WbcCs2j1WRG8DW/Ul8VbsZwBnO1EKrBGdnJWG8q53OLZR4T/jfy85S6u+FOU97qx/Rdc03OD9qCuUQGyhEpJOCOFXv7I5ptFWPDAwWk/9MyAobeWqnve9uezcBliWwitMFQ6d3lGQqtu5uTGBKZtcxq9ZSozRIUzNi4fh/u/NQ78diDT+DsqfNAJkCZQDXgpB5DolmhmqtCzfoaJAPSAq2tHat3GTpfKymiJoImC2sRbWBIVs98YYYr0AYhVLzXuojNbUrNejH837ViNhLdUPaA8dlh1kWYHLjKw17eUdPe7gBnMCvE6d7EzGaUsMYRzCDJVfsQqr5ilU7pDq14QzLRMICxBAEaOy4WQs8tlAfXH4/DSdNS1Kgdcg4ia+10b5PU0+cEZAJFUWJzc4b9e/ZDFgVYqLQkCEKLFXkDsxp4pMcd1/1E/U7JJbK1DHfcfRsO3LQPj3/0FGZXZkAmIDJSUJOh3Q6zZkBf6imr67HVoK/aRF1OUhNRzaQ+lVgrgZr2tHVQ30k/r9lMYugGcH5lHX8j25bkw9Ma+KpytMjA8gdbZuWXCwCyEn6H6yp/rQxJYbQ2AWne42fuZ3CsP6sbokkrNkFa+bPqR2YBltIiB5IEcAmDSBnQetI6l/1ktg31LWsWpgeNczMQvM82rQs+vQSOf2usnx34fdvFDBZjWYhBxArOm6hRngEFcOHcJRy8+SAkCRCpwUhOIMBs/DHxdzOASVtY0nBRlVNvgFJKFMQ4cMsB7L1+L848eRZPP3FOX0QqQHnmxyRhLFd1apHU+UoDuAHKVIhLI9yKuwphKOvmogCbu0YH+gt7CKQWHDLuTcVkrRxNlfDraTPNl72l2PJo+pK0LlJKx9y/yERqM4pRhOy2uVNOo800H9bl4WpWwwq20VRabM2sglYELEm1NQiQSimQJKA0yIFBpVYCQvGt0gitBGS74bTWJJZI19CVqV2g5r0AMXIFnr2/sTx0x1l90aYMjdaX8HZnefn5PAFqEIpK+NUyZ+XjcybUmCcCTTOcv3ABN86uR76eqylBPRABgiQGsbTCrYJsBjpKm5aZdfzAYYPZIteCJWhKOPLc63HwWQdx4fQlnHvqIrY2t1XiXCgES6QHK/RYIACZFnyqCYDCKKTgKblNUTFhAls1NEwB5et9ZzNNVmtzbaEJYFkFCVWwzCld1GMMVlYNMiFTNy3cZBSdykNCW3IzQLRVrs3RUO2PbfNqxWsGc78zMQDJYGSoD6CKf6XvhRJ0qVwAGxcQBJQ6kAvWz6UdkywESLrIhv0iEoirDtolwTdE+KxPqFrab2Hzm2/t4f0Weh4srakR3S25QPW5dumGz1hNERFIaCHXZpL0ZD0JAc7074JAOUFKiZvuuAE3PecGzGVZrQrMjCCZge+VI3U6LbQg6CAjwfqGZOweawTJyIRAnguUhcTli1u4cOYiLl/YxHx7piCpG6ysBUdNo2iPXy81rs5CJEewTPsFzhUg5XoYEFDzkzVCYotAqNbd0WvOjPKqJsrtW+ZKdYnqvmKYWjhjqjnNr9PVLLepK0NpV7ZKpaYA/YAg1O5NqxCdtMZ9IxDszF5pbhXWVt/5jhJAKcH6dmdI0i6cBMsS7VTxZmmVLpDhsRYCNVRzR3o3uSN39YUa1QCwJ/kGGk8IgjQW3igHQSoIlxMgNLzMyd78+vTZ8zh0+0GItVwdDpqREpRMCaKUUkNnB+Kag0SEGdAm1KanntidMaoqWzKjRAmsEfbs2Yd9t+xHuS1x+fwVXDp/CVcubWO2PQdKaSqks6xmIxQ2UIOJbel1y+yW7LaT3WlofzCDu9p52MQHlVJpipBpa0c7sp6OdNAUudIuteryBZ4qJMBWsCs/XsMaXaox93Uo72onJlLIiqs6GMtu28DsfTfIq4QS5BJAodGngBZ80vpSKHdBKneAJes4SeIdCG2B9mD6qomWTXEFEBNwwDER3vPWOjatv33CVb/Ukrflx4C7HZeIVX8IARakAm+Z9jUzAnIVlRcTYM4lnjpzHrfceRNKWQBCQBLAGVsbWz84rLKOAHRswawqZIt2FSwV9m2AIGHcCIKE2jwk9gns278f+2/dj9m8wGxrhs2L27h84TJmm3OURQmWUgmTUIIq9QC2sxMMBU2D7SmsMCnr6aIFbemsS1G1t61fDZ26a+6rQKKamVUCSqR2lbFOY2MIxl3hau2ERSEEKMFyeBMqQFodTGP49ay8RR5aWZCKlwg9w2SmbFVRTmWkbhNWuzpZAlQAkBkgJUAlUApdZWljUkIAzJnKgCUgJFhmFa/RgepA/RWlvLe2YecvBT6HfosIv3tCUOyo52o6zuTBtWcMAgk1EJkyNf+fAZxJbfGFmsudEHhKoAlBZDnOXrqMfbMtrB1eR1mqff6liZoLwwxphaAsHGmlT3qpKkGtA2Bnjl8pAVUfaSy3tkcqcmDKKUElgdYF1g7uwfTmDewvD0LOS8y2Cmxf3sL25gzzmUQ5L1FKqf1SaOEFFAZR1sjGBYwy1dwbFaVAeXUUWqXgjICLxjCugoElVCMaASaLMuzwp6q8Wv/p/3Otc81iHYHSf8GuzjVLcb2oewWLTM4wZzZLUG08WcBgcAzDBvjABMwBlFIF/wqNEAsCZoWuk9QugXIfWf2k0Zpad0GcganoZeA7aRHL3yrPLmpTn/JG4ph1D+RRSxNTCAB8P8gMVEBN0TPqwl9NEymftrZBw2bpBP0UHAAZYc+hJDUjIANoKoCJAE0JtJYBEwHOCU89fQG33LwHZabZydRwIuNvGmkyq1HAejerGnRmcKl1BAomEjFKawGNT0yO66CcB4tudQ5KRAliT47poQnWaMMsH4AsGcWswHw2x/b2DOWcURRzlNtzyII1CnVWGOrpzUpX67VxBjUxwQQ1iSZxX992bGbHjFUyTiRSgTCqZ6Ghs5+X0a0mnYBqI2k7V7tacBSqM2AtEnDHlFkr4P2krvVWqE4NFVJnQpYEKgkoAJQAFRKYM3gmwXM13kgweEYAC0hzhJyzGpiFCg6qCRKh+QYWEt4xKCTL9hlVv+sPdRcgZt39jL3vVl/UNLUPCfxilEBVYC3UclTTHQQHUWnoz2YlH5GawxaoAoKCgKkArQnwlMBrGWhPBmxkEOsZtgRw5tJFHLr9INR0D8DEkI7fKaEhrIahwka9yY44xQNZl0BKdnjX6ID04hPSMwi6wZQSyHQMQakC00LWRxc5JjTBFOvYIMD4vmVRYj4rFEKYz1HOJcpSQhYSspTgUupt6VJDXOFMLmYakju3HNuzEpzOJ6gouTcQzIIpQaRdIq6PGYKaaiNpLa5FIAQbfAREbVbDOCf1FYLS0RgCBpuZLjBBYxcXGCbV+0aBkBJaY9ULVi7AnMFbDGwVwFZZBY1VgMDWiTOq/H895RldNLlqZMaSIz/M+lDQRXlvGo6EfebOQFaZcMWos7BFaXJPc5nVhM7pVQp6M1gQWJAK7E0BMRXAVAB7BOSaQLkugb0ZsJeADYHzYgtyW2Djxr0ozP4Ap14mqg+QuhSEoGcBFDqpoK2Zy5aOklKWgcAqKAlTF4MudMxBkhrjpIJMZACyM7dtmwzQSiTTgpSBpECGCYQEJgQwM6QEWJZgyZA6qi2gFr2YaTAplWBJKVHqOW+Fburan6WElJovzxJLaEQhtatg+063hYSjkZUzYb0PdrZ7m5Eptb2mshoTBrbDne6lauZGaljhtpdlw6AxpZDAAigYKBg8J2BWAptlhSSFblewgvfMwDwDuNDLgkWVvzOWnRUjwBCJaoXuA8llxWPLzBblHHthQB2I2vbvt3HnfjSdF2DACI8Reoa2PEJBbO0SkMiUasuh/P6NDLzGeO7dt+OTPuOFmJFEvpZbxABiiI3MHhICLUSuAhAgkMihrLZeE2B9W2nTwAqJhFSLhvWCI6GsJRvUoi0JCJIlquBjBWcJaqEMkVDxBHbagPVwI6U8SpR2EZ1CH3pDjMmHBDJkMPsg1D+pogjS1CAEARWVkErxMXSjmWAnWQUgpUIaVS6lDrwpnliXafR+RjmYpHYDNZIwi4lMEI6UAlLXsxMIepZEK2QCoeRShw4yMKQK7EIt2a7qo5WmVoJCR525ZFBZQm6XmGKC973nQ/jo+x6EmAqwLEGlAJcqUExSrfVgmQFlqXgUAEmyC5nI9uRqUVOc1A85jDZdJFppOqqXE2SsIKrx2FWApQofMpEej9rqk0IAyADK1VQgrRN4IrH3pn144fOfh23MQHYAmxLYKY1rfxvQMrl+VPvWlkulqNn+P6XECk9IGL/ZX0FBET78fLqowgbNbcXm97Z8ArPyLWmrfF0UVg80Nt83N0fXxbCNO7K8rWMNDzzwqIJRJMClBM2Fii0J5SJSqd0iAbCzDMCIkN1P4FeiraKd4z9E2uD5cutb/Bp4NkiJ7fO8vjinetCXl3TSQt+2EsprwMqymUEAC9PUNFSmoT904I9V9D8ncE7KBdgglIKxKQvM5VyvYCOzaNDWnbVlba+TscK67ajs2wjjk6cja2OvSy+b5cHmbgJ/ABuK/b4E8mWHHYebzB4GA9u99zwHRs/amF/D8/ZmC/c8Y2CfAK4I0FYGZIUaUyUAkpBCwkx9qr63YV1dmhm0kcqE2jRZ24c0RdMdCX628lbnLw8OjjRz4BWWosa47j8F6uJrruqBYwHI2G6zhp289DpYlykFQBMBrDPE+kTN9EDDcZM7VdN1Zk65m9z6DlHhocovQNT8apuxkzXNv133bBBW/cScWFkNcsPxsaOVEjiyeZFrvaVTKXK+N1kjuOnMExHmSc8i0UQA0wyYQa8iJRV3ENoKmcVhJEFU2tkQiXrAekeIfUHigOxEyCKAZZFdB94xANoYdrSjDQY6I1rt8hI2MQF2epCNksj0dGBO4IyhVLkfrNHf+3gwgDOQer2ki/QldhEFMAS2Obw0cOgiIzlipRbJi73faotGEupuk8TSOfU308g52WlkBSAI1s5rheRuYGrLvVZM7Le+RpfZll1Nier1GTGjzmg8y63aMhsyUjvLhy415qQrW800EWYafdvGChthJ9jdf0JZcFCmA8+6IILqTGEizKytm1eZhYQwkUKrnWqN0peo8usCuXa+F+LPts1Om7QUHRzhuzNXtPSvM+ByALkE6yXZ0CcRqQ1nBVi3DZPZeEXVsQlLJ6d1nLhd8j2VrtxpGowAfEEloNKIIeFHy2/+Y9+nYf8FF8Yp4WG91ZThZECsdwLq9fokIvC+T+85AzDgg+4aOXv7AXgKLp7ObPSt10JD62Bb+fVHi0D2aR9VZtU/qYJuFKDe0+8r82p/shmgAUVQWSa1mEzUkCTp+yRVymrQ241UpOWxdJR4bJiFjFuqPvN9DHLKSyVPFuujwcyvJ1DVN1T5RoymgHkWPtgApmz/vRoidYIXZn07ALsBiAE/wGNBG+ulm5EA0CCywj+GAlgkD29AN9BNd8lN0J7oCzU2cCxAjCovrcg5aLEjbcXegInx5RoOdyeaHkRmEZjaCi5RGRupUaewKx9t2+lh0DygxC878NmVh65hYJaGtl46kkpKZgMrdqiZL0c+G4VRW5ZZzyqZ3FmBGDpwoE5tIord3zQCMYdCGEghoZeFLjpgGb7lb/Ms277XqaXiUVZct23YgFgefklUIoAjgEYoTb8577uCG1QMflmEulLwf3P/VXEklKy7WE84Gl/bwm2T0qwy7OLDr6vzziJDcWGfQ9UpvmRvYP7VfvWeeaaOX9fNMJrXfqZq7DDUCrESeqsnA0V491x/6tZyZvgnlzeYMar+WB9vmb57CqMhmN2DqDrcg/T3+gDxLFKnb2/IQUY2q3oatTRYqvHCqBY/mXec4JvwPCClswa2/QD9PwaFYwBusCCgROPjn9sr4cIeXxO6UMjzU+zrzpLgKv6g4Bnryz7AZBEbpATLAlRkwJxBZcsSZTun3w8+u9VqS1drRrvNNWHJdBvVpulaFG8H2aNByT0etatcBCys746Y/LqgsSNk5n3dRrVIhIu8/H4ymwxc5GDjAs7z2uAJsFIwMJfgUqjzAUqulhqzVBu+WLkHEs7aSTsb0HJicE1JY1BfDaLYQCUgV8E8dsYP1dowSPaZUYEDFj+2IQS/cVylw2wjV9VMI6kVWoIBmdtt21QKiIKAGQPbBJrpjgtCHzOAqt5J7StfZbj93ExTOg8koI+/UlUzCrTemibaUQmcOxfutEvtN258VnsAC/1ZreGvBFZay6Ygk7uMNoPeFqU5kzDbgxsjnPViWAYgTJ4OF27DmM9hLG1fMqDGXcMSx11QvBsIr2sNu33Z3BJUL8/cyszzEthUuwNRlmqNV1mCS3WakDpMBQA7JwmbscKpCrQ7yagUK4/Vavmqkwx2HuK7L4PcniZAzdYbDa7hvtSRY1Gd3ENS6I4D5BwQMwUJxLzEGq0pY1eDI/VpLze+wPqXSpTqWr5a/myWq1Zrzs0K++pt4bxrNK7drKpThdtTrU40abzjwQC75t+VLrOpqF6XatecMoSiVl+VLq+Ukv2rzt1T8yi5OtxEK5KqJYU1IFJbfzVdxrrlMq8eqJQW6U1T9nxmrUjJaW0XaqM6wYBtzav/V0eoSb1d27SxeiuzM0IqjVoKPIGYM3BFggoBWVTnAZjgmwUh0rH6bMbEEmVhSZTX1i5jl6tQs/TxRNXaC8O4VLu0zEmvUmlrWbCCdNsliAQe/dBj+HX5u5BTBq+ppcKUEaRe7CH0CUOsdwWCzECqNJH6pEWJpdpYkqmDPMtSb0IRudqLjrJ6TgJSKgRSneqj8nZFFtBpVOFKoNgcSmLaQAsIkbp7gNR5A0JkahOQReaG70oY1EpKdgKqagWbMAKh3yeqBNu0tYReBivVtJhkVhtySFh/GIJ0iEbqAz8VH+qwY73dmaEncozCFQ6/RiFV6NLuPJTVhiVGdTWAWcSl9oVpNaTdK+ZC77RU39XmLIGtc1uYX54DJUPOCmAmIWaEJ/7mcQX9t0vQnEGFhJRQ5waYDYqSG3P/o9jBEFRfsquQ1wpeBfIhovfIFXoy01ASCm5KobQ1sd7lxQr2CwkIwrmPnce5U+eAvQJYI7XkMydgAn2OoM5asFpBqKAC7GUetV4Wao+9QUwGPVmc6yYl2Is73IFt56XdGrpQXHiDwS3fIAiBuk/r8WOfs8eXk5dVpqSXvmpbKQRIK0aRC2QTdceByHPkubAr5DJhRFZZSsnGBdBKilgJja5DCQ3ntQQLFnZCQ51loi05G9SnUJLaklxFBewWBhgIr6pLMItzCCir8yLM7wAgZ4ynHnwauLKtXMStQkH/bVIxgG0G5tDjCOCytMLPWpFbppNuBW555sufL/Rd3xeg6kSgiNDtCkV4UKcDaTXAUKsAWX+RrGMAUP9KCTHX8E4IgAuQFBCcq4E6I73qi4FMbwUWrBSJMS3mvAFjkaRmTh9jVD8aXiuehlyR+qcHiT01lyskUXc4rPmGAa71RiGrCMw1ZsQMaYTGAmFh28Uei2Utv95P4W5nsyyYQ9AIpQ6oFga263YhQcgzQjZR27DzPMNkbYrpNIeYZBB5BmQZhFYAkiUklyBp4grmaPPqOPIK1rs1Jl1dXV87Rs13VRcbjTePhVakEvoIbxcJqW3LmRBY238Yjz35BKgQwHwCnhXgrRK8DXVcWCGBAuoQEdZtqXU+S3WeYXUKM4dlqEueasLvtESbPA6V0YChb84CLBlyLESWL3PGm7FqyjqThFqNpeG7JOjzAkpAZiApIedzfSQYgEwP6kyq7Z6ZPsGGhLP+m1CZDXKgJwGybCpvC23VykN7wAgrl0C4V3oFd9952lhUnWHVBVebY5ll7QwGlQVZa2zWPphc2eRLQHU9dmBkENQA16hEWXJ1QIaExEwqBVattVAnNIssA+UZ8glhbWMNa3vXMFnLMZnm9t4EMDRKKGD295sHwlFwNjKj25t0u7mNbVwVYweqk4R0G7HJj2FUbsYELgrsFRmObOzHqUfOIGOhDgeZS4Ua5yVoDrUuQLJ2MVV7srNpypxG5LZbfUBEfg/SglC8raxI1pUCiIyDlSBHSAzCZm2oWQu+ucSRwPpyB4BJRbPJHutM4ALAvFTnBWgFwCTVbi9z8COVVohqh3BAQ1oQSrag1zLmevNwLLK6DsykzSrl1QgK1gXZhvkog5kbV8/U2XpSj3p7z53zLmwZ6oE7NswKOzIuh0nAGt0AVpKoxo1eDYeyjk1I5SNJxUWAOealxCYuKeSQC+TTDGtrE6xtrGFjY4rpnjXk04k6YKNkGx9Ru+1Q8Vdb/GXqpwYAATquYI5nrXg2s1vGV5cE3Qesr/9SiO6GQwex+eRlXDpzSRmQglUgsABQcBUELHVTmfsCDBJouFI9KSZ3ixjhViPuPODQ7cCrYv1D2sxCWQNhzXps0nEArQCkGQjS7nCVUgk4SgIKdYgIZaSOEYcEMq4sfmb8ysr6WzhK6vfGuS/6fj8bwSYBrqVhgJQVUamkzkda+dN3GWk76EBLdz7dbF12VqeBqzMSfFLog63irCcz9XO1qy7SdoGe/tL1B4xLoWfBNSQiVGjMTANqHASAMUeBudzEJVYnNuXTHHv2rGNj/wbW902xtj6ByAUkkzoBCFBHotlj4/Ssgp4BEg4SEkJAMCshB2t+hfbgpA23kISdpyCGCuwR46ZDh3DpY+f1dLJUJwMXUp2FaBaSaRfALEKr7h5ssZrsfY7JVkNzJ74XyqcBSWOFKVreduAQtVXGF3gXszoVq86lo9prCp7rcC0zKMtUr9cCNqyPDlNHOUkhAFFak8EachsrT/qYTrULObNwnqXKQymJaqDbKTFibS2FPprLMK+OEzMIgEzV2BwwYRSGNL6EqiOX2pUh2xbVO0pg7An1ZCy7LtIKpRm7egCTQR+xTqk0gXvuIXQZ9ohyqtKrE9VUENDtTIICZVK/zCwx39zG+XNbOM/nQIKwtjHF/kN7ceC6fVjfsw5kBFlIHcGXIBZ6SlAdvqLON9Q8aaSXmfMXnTqrJeEmVqKQiwoGqhkjLhl71tdwcM8enDt1ASQydQSYWTpQav1blOo4cLPQDKgUAmrVHYd6uQ4O+emjykX1e7cC6KOBuqgtn9gYDLBjP+tRLaDP2WN1wi1JhjqcO4O9xov1wZv6RBeITB39zKUWerNj0ATrMuUGsDmjrtDQk5RrwcJCTYDVXQLK79BBfAmCtKjCKIRKq1XBOqNkdFZ2p6ebv91wBXP4hBZGZpiDSP0DNlXXOWsYnFmI2oFZzuo9Bsxt6hUJ3Q5O4wu3I6jiUfGslYP1lR3eDHIho5zU7MjW1ha2zlzBmY8+jb0H9+Lw9Qew//BeUJahLKVSgqpHNZelLpr0eqpqfYP6K4021MUq96W6UYG1cWCwJFx//WFcePwCuJBasKHcADbvmpiCLl66U6mIj98UQW4BEa00VElYZMnIK/zp93pCHqnpBzMaINOhNVdGw3cGmLVAldr/M3PpgkEZa6tB2vIrK6rm/a2MgUGQVFYCaKabSJ22a3xeF4azvm24Qi1KIFS0XykB0qvwKoEGWBaA3W5q+sC84RgYO8NQXekFknYmolpsU6n8GozXmVXN5o06qztMPMG4FSrI2AjAua/ao9KdUyEtciP72UVMFYLTC4pIr06cS1w8dREXn7yAtY0prr/pOhw6cgCTLENZFFrJsJ0B0dpFrW3QBbHzu1n4JGw8hBwFpRiSXGLvnj3Yu2cPLj59SR0qK6Wy+NodIabKEzNKoQ/F5KWv8Lelb5Mz+5t0fiKtAAaroNUgButYlkYBUH0v7dyzVD65dASP1CEi1UYw6ZwwZJaN6qFKVTl28JI0UTjUBa9qawPR1f/VYKwEWv/O0AMasGsbnNmBapW2GcDVqkWGXpkGM9UVEVDX+jpc1lcKOljR8k2QJJ3pLrfNNYvO6wydTs88qHxELW8rtGbcOe4CM9R9Lro22xe38Ni5R/H0I+u4+babcPDIPpSy1C6Y2cqq4ym2B8zOhvq6C6V8TJ11+WYvhgQoJxw6fAAXT13QJ/+aZb8ajjF0bInBsqfwrySp/s11JKQ9XZ/fF03bmQc1+dXBN7UVXgm5XaMBJehCSxJpM89gddWzQQFmMAq249+eNVBbmAIAJewSX2vSTBSarIFXvGkutFYSli+VvhIINvADNUE2ZpONnWetwFQ6G3cwg9RROoZsHK2WtWsvycnPvGMUDipIXEtjTLoWBnMnon1Nr3UgBdXdsIA7Z1HtSNcJChV5Acy9CAJbl7bx0F89jMNHDuCW596MLM9QzEu9ItzwI+DgDzseTNaVXjWjQvEhoKdSizn279+DLMtQFmX1kkQV8IsJf9v4Hjr22+TO1/Ox77E8KjBkEMAOk8tgyGi1QSVrHZuJWHeQWcoKAXvhRkkmyi8r+Giu/HapNNJrpuA86dFlE1dr3EMVq2C6/knfrsNGUHSEm/XNOdWMBqx7U92KrK2qEW4G1MhUo9qeA2eKs4gl0Ijej1IrEbvvzig7BzVUakHPWJirsAxKYI2mbIdWbVabtq8xqX8xQVL7WhVrsEIq1FVtZx87i83zm7jjBbdjumcKWRTqLkh7RreDaWp8q5wq629Ql7SLk2QB5JMc6+tTXD53Ccjy2pJfdRHrQKTcJZDu776idpt0DHKqIIPTgCkZ9GUmJPAU+C1UhvlMsQSooB5DCQQAkioyLKi6d46rxek6T4Z26mtZu9DdWlvHh1R5qTLJbwxtJdkT2Moz1YiLYNcG2JVuWqFUB51Wo6GK0zkLXAy6sOihUl7Q1VNox82raqoqPwObzUsOAmDHqhrf2bhLtSyl034GBXkrI9k2R8UPmeCqyyNV/yfoSzjUXoetC1t44H0fwXPvei7W969BFqVavWnfdGZ9YJqlsvoVv6S5VuPE3EG5Nl3H5fKyXmOi669vOfabMZlMl8SMXZeCcMnNI8ST+5snR76oEaXMAsQKT2UuRP4z/3tKI8dOP9UZqriAjpDpAJOSDf3MuIgGyupyq35yRy4cRVQtrbUvNTrR+MxGSOuWsF6KjyCaGrFpINhZo6D5l05+NZ8/1ki+OCh0ZAp0AZe1oHZGBDAzJDUG2QXgxn67PBh4Y/gmJybVtBKukgIIKNXagPl2iQc/8BCe/5LnYLI+UZu+HJ3JZC5z1afkButPTvwE6tYfQK0DYKVELNy3zazrE0Oui9KYeTak3RmDTnOMsw4gNMZiv41NrszYgVgNTNbf1XSf9gmI9I5B1NBFWPycH9j5Y5UJoKcbqgTaGttnACrJ0UmMshHqWfXUaiY7i+XrVTa3Gvnn4HlMc3DgVzk13yDnqf6/jnFUMQ+Xn6YJaoixWVzlCn6ts8j5LaysGiqScsw3Szxy/2P4hJc+Vyt7smiKjHKx04Au31yVyqaddMBYaB/fzu/XW7+x6i/JUC3xeeiZ34RRI6leznvDDjfTkPFyvw8ReD+fFCTRZeTMGHRuenU73xysQ+ZZSpvUCgDMvHSNMWIbOfaPDbGslfV8zOXi5nUnNz93hAUqlC6NwunZUVBtKqWJU/xzBurPHYXZk0OmApQJXD57CU989Enc8rxbMCtKvXIQdhkwwBYZ+WW1Dk+L3gA9j1s1cai5A5Y1+PsiBjDlXb+ckOvh8Mjk3ww01GqHEVYzjxStGR/P6eV3vastmoWJdbM2AlLhygJZ2BDONKbEe5XV9lZscA4qY9E0LnVMpQX5rqSQmYFJhqcePY1D1x/E2r41fduxanOjBDjSPhUC0E+Z1VoBozicKcTBnRSSgWWSr6T8Mr0xoGbBu6wteb/7qDM2sHytE0OqMVpmg9XW0S+pIB08sn+XSYxmh4e+rzql1ANVuxIAWZQ49ehptbG4ZOXLm1kTqYRasNR/q3/EfsaOqxIar21WPCQHu9H2MVl2+WPUvNL0UynbhN3QUNgfK9AszVvIeu027bLkpfTbKlInEtXR/kzg/JkLuHJ5G5kgmFmgdBOt/5Hzr4sX//UU2sk+6EB9bsuIweMzpK1dWrTCJnhjA0gjULpzH8tgFDaCtKjyDCE1//lOUp/6tPipXUREkLM5Lpw+ByHIiZs4azHCb9YKIsTlf2HaTQUccwc0iVGZGyPYYfKpDeYOVUsC1TxQV97u0tRUfgi1yyNWzaQm+nxLJ9co9G0mD6am1kVN6RIunr1s12a4OLfzth6fhc6xhrS6+XUZ0iZ+Xl1p3HJCLniAhwEH07uQKcCcWxiwuGWLZkIBwe9oKZvFkF5g719LkiHkCwAin2NldAnQTpEZHn2sP3mf+3QPAxACm5vbKLYLu/25ethFstpWbdyKRRsvJvSh3yjwL5RfV7uEYH9oyHpV6+cCuH4SGQFckplhhj3gLxio63QSI9Fbc2igyabF96vxcjVE0XaZnCZMbq22wJX7ucPdLOcFtjZnoExvBnPSxlFAdQ4DIPUGIL/wFaMurwbojAG4tODVNLqUEKz2NdwQ6hNjSBJSDxdZuGfMVqg5elRgLO+gTRBS3KxV8FL6WvHQ59SitILY2p6rA18CY6GpBMLmuLk8akFaNE7mI+qhFCnL3wozkHbBOnYdxeRCS5/IFf42oh5pA++mUErT+QKy28I9JoVcxVgMIOriKKHf3tw2+5VUMo4rAXXIaV27mivBB43nrqD4GORa9pDr3VZ+xI0YsBQ4UsIYWmooH2MGv0gvFwaGuzcukuhaZ9AnwOP7jn35WfZ6hCHk1g1o70sf2rrfhUA5V0f4OAcBNYsL9inr/3N3f4UoNIOxiNX384nZn1DbdOXnpCeoU/ETmCGnEK4ztpu0rEU8Zmed2TfQp97LiomMkm2ilo7VYWnt7X1uE54gulMSoo4OG8Kj2VsxQv0WySLkCqUE/tqedyiJ7r0A5HBBWN4g2EnytvYmpQU6/O5VcLwdCg2g1PhBrB473f8xq1ermxfA9fh3L5PpKszG/+3sUiwA3cJT6BlQCWOPAN2ySe0F6KSWwbAsCkGqZRTCcAYPO+VGZhRatTG3C8+uUSCKaE656EwferZkBZAiILEhSb609SuUxoiJL0I7OnTUWEiYBuwRAbcDbNWEIEZaEOzegJYoSgNyhrJracwxEYKdgm2ZhiXnX+hhcMnrLqIYH9r3DagxYzLJdQzHf9SRkXb3BCSEcAMIhKQFZm3Z+8HN0O/LpJYyBJIOBOl0eqvBZJPxeMZi6bEGTrM6hkIBvtrAZU+43KhdYoP4glCDjr6QmvbnevadStjzB8YQfrv3f4ETcxcYM2t7p4gd2xVzBSrZFPpkZ/OjI7UmJhSjUNcGgm6jUmp+oXZ1eKtuB471vbGMNhiWwNkYfqLP+Fi+U5tv3MlTgjXwkUIowLUUP5AS89sJs9NT2bVl01qMUjjMDMoz7N2/Rx3oYZVZPfMQEqgZe/J/7DGWdxo49TWwbnot74w+C4FiC21qPvRIwr8T1IH4m9TRw7W8Ym0xcJTUFMaAdmbp/PPcHjsoUvJLgNJAGH10tTWjvny4ExEoIScioJQ4cHAv9u5dB5esr/9KW9JDUMeMCQCQEuW87NkmiRQ1sOMV0St/fahtdT24SRxiNAUhLJNCEHGoxg0NrDGCjgSo23oJzcMu3Ci1CAfh/Ei2e96e3/59g421Q09D5fpuSzSjerExAUmdOdFZmnTsfvefN97TC3ekBAnCs559A5glRO2YNEWyBRzZ6+YJYCkxm801M0tYM1Fru0iaVJe3V3wkwodk5A2XJ0StDI0o/LryDXRT84FHKqtlYNUZiiVuxj4qnruAVSQI1+CD6wOir+C75dXy9X/uk2ckr1oS0yDs8O4LpqcEE+MvtY07RQki4I4X3Io9BzZQFCXsxQtOtpn+Lr0yMk+rliWrPEDjGf8UVDMkztXXBQgSOwuBRslwEA/eAEd9+7/7jDGssRzLRW2D3h/QbkDP70ifjxhKCb0XYC+spSMVTVbWHpOpwTbLD1W4nFHns4EaA5V17itobriiJoLwLJFFBOZ2Hntbj1Ise/fvwa3PvQX7Du1FMS9hbmT28zWXxPh1tged6m9lUVRKpIv6okZ3zIRszBADl9KXsXc01YOAY1nXLlrEmg9+RwBlCZ47NyHZJb9ZxVQIflRXArUIsecKsS7TgAF7k22g1+zaVV/KnN8YYYvLpmyDGBwYZYsJKTv9kP20vkbWtyezi2pCPolZRlO/Cqx2Z4PwB5lXVyJ9Iq/ulwyAEKBMQEwyTNYmyCc59uxbx+HDB7Cxfy9AjLksQRrLsn6PzAfLb13S7GVqBBATskxg88JldSuQcJaD7wb1NXILGO+dvR48RKkVTa1gQLkQCXBRYu/1e3DkzpvApb5Pjku9AUTYu1HNgKiuv61bQVZ38wKsLpNQhkwLiinWnJlPAlmmzlxRB1YCgL6FGNUVZNVY882K6llrYAO+POvPVu7NKbhC2IFBRE6zVJdm2OPMyRUK81y9LJlBKAHKQPaWVAlwZttITaPrffX6DgZo2yqZwbI6MZlI38psrk9nASZWJ/qSvqZLlsjzDNlahnxtgsl6DrE+wWQtB+Xq1mYhGWWh7lrMyRF+oyu1wnSvA3PuB7PtIbQWmKxNMDt7DigkaBo/zzhIKQKbKtTLRuFe/vUgoEmwbCSwLMvf1nilxL7r9+K2T78d8+25zk9d392YHmIRgLjqi7pzru7j2zs6rKXJlJzr24lA5oIMOP9nEDKoy7kcmK3rqoReCZJggElqVWDOv3fahYHqJiKlkIjYQQZu48n6+1AKsuLdrVupyxTwRaJWvL4DQd3w20xT3aRLzv/NQ1W2gL4aDVxNTmjFRvqzZIZkCVECcwCUq1LaAGXzqecPaJDCArj89BWP82CG/ahr3IbcKr+8ofLo5x3gvbkOwEeofQpfBNqPQaFKOlazZGB+ZYa53jdulkGyMFbcSJC2WEGo7zyPIGsmtSeVSgbDScsVklbHVpew93sHSSUWEpDG+FqZpuZ7PdqfAGfazb3ToPpsIHIF7yPltRUSIWa29zFY74tgwy4W0ZC9/rRSMKS373BdOprs6P51AI+fWALIMmDr7BVceOoCMBE9AoALYG8/myHPYmkdj9BSQy7Un7gLsCwr3fq+6flF8oj8wFB3vQso4Seqju4HamfB2esvmMNHW3XUk0wQSXhJtcxKqj4TRHUPX6MQzY9B2/on//LQVL6CRQDtx3dR44P3bJjWV64XVwpNU+YE4GLGzyAu49oM2wGo82IG5TmefuhxlFc2QWuTRPefwuhxt4gCnxPckt2PAQDQql5/HqtBm8JhbtmtSon4ek6nVvA+newlmqFnDcMdAs39ygECysBLF9ooYyE6ebKsn4YPY6ZAnmEyRii1Z0OiH3rHVTlhG9yOm930RIRyq8CpB04BmbmWrVuZ9TlsdNcowXjFFYDvO/StrwtDOt/lYXJf60nvWaCDFIQMqco4kYbalVCbgRlBBzDwviNf1wfXEuiqJp+GnIzuKohKYMMWm5s/AWBPyXixjxYl4LoYVgH4OpkIIKn9fOFAdR22a1Nquipk8tFjqH4ZqcnPf1m3tGRM1ic4ff8pbJ3ZBE3zsEUPjGFz43AjHZppd40S+GgqADdu1GzL/oUnv9tDA4Qa2ufTnw4DQELUBiw3Nu4kkBmkaHdXjBIIKYnalVS2eHdAiQa8DN0x2si7oyqsYxdEjNp0XaOP9Q25rblVA8Tcsmt+NjXx6x9TjNa3Z5OLaMyM2stUY54IXH7TdvBRLlBcnuOx9z0KZBmiNQ7ajFDHdhe7NPKhViIv8ZbyEUAqE2OTKxe9FBKjEbwKrKG302ZuGjgWTLJzwWQzXRcP9pJKU573mg3WOz4/IJ3IeTi9n0/cFw20Q22uHjryztZFYnPrMQhKGQkQZdU7+mRlYrZnZtj3nRu12/STqa17wzFBCbgR8oYSoapfAviuFsdpI2MEJnmOR//4IWyd3wLlzW3EVxNF9VKoIxwStYS1nAZSR4EL5dtGMb4dqMYsIT13g2ufJNiu429WhAB9dHSqy9KjMRqHVLa812IF3TLr4MZThM7P1tI6/yyACy3hrcHEJgmooKXwBDUWU3BdhFiL1ZCPy3ft17TBy5Ix2TPB6fufwKkPPaUCf6sSzBtItn16ym/dBTD92hNaLp1Crmsfnqzlp0bdYgdIuqjWZ6Ufdb9RDW6q+en+NJfLWzBXvRagusSbPQGu8iWTSyBgSbVf3AbTnwOHblQpGMThnXiBnFoP8HTTdnU/ow0FVSQlY7oxxYUHnsaDf/ggKM9rweFnDLnVaWngaiFQqP69hMx7p4cfkkQL56VMhgnqhQsgkMIItsAhUz1Vc/a7exUwg9jVxAwi5Z9ayxdzVTV+ruTTvzWJAZS2Tq2RbC3EXBM/FxGwE7TzXtXFNdwdNIdZareKgA63LZTSP6zqsrYxxYWPnsOHf+fDakmUtzPTXfXdi8FdJhtf8Run7R2EFgLVx156A/gGY4yGG1WJhCFicy5doBEncHe3JZD1XRPeq6VraTxKWCOhtr2GLTC7jrT+p5BAvBbN9Qlmu3P991CwMwjjIyWFg6I1TlTZvvumVw52DhHJQC4wmUxw+i+fwAN/9ACkuRs7sHFo6cZsLHL4rLkAiZ4nA8jN8ktLA32JpdFoja/gdef8rdsUyrwMWgsgnLyir+rFSHDKMemFgite8nY0Um1ZiCgw9Q2qLbr0CQVmHjx+Ym6AXsvbeBzpyxofxssgU55ZGhworE2BsXZ1BGGyZ4r5hRke+l8fxpN//QSQ65VVMS3lZ7oM49ZGHeV0Gnef3xYZWpGFQBFKgDHJ+ZALFclOPZnVqADsoLHIEAP73rgZMaiuw9m+tWPAWU/fRCwpTRGaJnTX6ofyjBk65RC5P+hKsebOUQzGSseUUK9KAPUlwankbIoSeYYszyC35jj1F4/jsT9/BFsXtkFruVVQvagt/ZgIIdFyA+OUmZsBPxoNzSsmYWO5Ek49GzcZmg7Ugl+hZdI+N9fnpVuIBFUIzLWc3uEXoTMPmguVAiQ0dA8ZRMedYB+5sPqfFlO48RATD7AxBpe1hi6jqp10maq+atOSOTqSmOJKIJGsoPpa2NTEeUaCIPIMIhNAydg8u4WzD53BmY+cxpXTl4FMVMLfRl3jbZluwdjus/89kO/qIICluxyqRVwjqGWibjVJ3w9nrol2hNIOeDdyrt8nABBkEYUJyjAqIZKslE/tZBqjmIzgptSDoFfJaT5sWWR3MZtVdHbdvJ6nZ7MGH7VK16yKOw7delStJgFk9nfhDC6rbzSEN8rTrVdQkZLznnR+Eg5iglaSur1I6FpIoNwqcOWpS7j85AVceOwizj95AeXmHMgFaC3rFSysaTxyfoP32eN9IVpU+COKsivP8M1AjdNvOQ2LdTXUbhKrI6BEnoFKtaff2iiGXpACSKFGn9loYjadkB3QgNrLDltHcqypIoI6Z15YJMAs1dFUgqpjKvQ+VMlSnx0iQMLRKJovSbISRI1Q1IYjtUWQGRCkFvAYZWLKAMxmXlZnElS1tvWSet+8q4IqVGCUA3vbehWD6ohD9Zm1sJrRwyxA+uwD2wmmFCnVykyb1pTOYKHVKKu8JBgoGFxIFPMSxUyivDLD1sVNbF/YxvbFbVw5fwVbFzaBeQlkOZBnoI28WqCUSuT9bfpF9b9j0aL5hXh0KaJgCJ/1CfXWia2mCq199jN3C+itAKj2x/iaoxEDk40pNg5sgLm0g9r9Y6A6e5bf4mK9aq06dsoBxo1AWwSDOcnsgiLt8JIQ1qpZi2XNp0IkBl6bszmqdpNWcTAZJECA0PVgQMoS1eEYqOrYQCRG+1RtYKcnWXFhIb7ZvWdiJ45yqLUDCf1Nt523DNu4JiydVYta48mSIUuJspSQhYQsGSgkoBUaBKkDUDLY68E5tHpzCK2aIXMpFTWE5BOqvXPrtI0lbabB+jZaMDo/ogYgYL41x/ySPvU1IJC2yJosUxr66U1c/1hDD/pHO40INPbNwkkP/dxmaT4bQdY3CHFZzzPMAFyhVV9j9dc8NsaPozjtYoFIFkHsyt5zzb9GNyACphmIcvVcGiTH4HLEvmoCl+4qrAqlAHZm5MYS6F+GFRbzPZLfjw3skQWPCDQF6pO99fLYAb3qZ2NqfQHx8jBt17oenTva2MBgqjWJsY7qiwPDtVtS275s01ZWvs5zixJp46vGUJfpcS07Vb80UBIAKuEHCdzJvVorG0UTm2Ycm1It624Jf28j2/ye1761auklMNSZ39joRLbIX6Xu68bRWE1fCcgW3nwF4VrEtro4PNQMqjv/7/yNZNUw7g2LmkoBBdf3PdfZqs2E6DaRfvp4ToNpGYLqV3HVEECIfKRJxgUAUD8GhW2CVt9/LKaMjx1SUVZ2lq7v4xQauDF+GoLqf16w/GcKPRPqdDUIvUsev8St04Bd1qqtkAF+s1E0RunU/M9VGSyMpkVNoYB/3VFM4zU3LwsuVqVdBlBtPraljxexrq7XM0ZTubysovC3tVXkd3Wa+qjauGeLN4Jw+j32ToxcGerDj+c72ywWqZMOrI3tHiUWDWDxwR+Kk+y2P91FqzYMfYrx19Ge4y8EGtViL6HVQ7G/ZVJI2LvQTSjeWM80LvzLFCSjjxf1eWtTgAb5tZSZwprWi82y0LRJoZmftrIS3ks5Bi6F7GTOkLz8YHxCHs3zABbIbKkU0gV+gDvl/T7vLEwxpk2MJZJkaN7L7qsx8zcrIMdAn74+jAlq6Jn/W8hAuIovks/oJm9IW4eUXUc+7UeCjRjH2nEK8e7PQu1KnUxsZaCLtIo0qB11OyyjD1LzHFK2bxjHpmXNVETKSj+xwmS4SorA5SfGl//7qvA/9ik0q4LUdoPcwNxYAjpm8HBR6iN3IRctMiYYvgsQmu6+WikyDV/7+0yoJ7D8QepCS/83YKF2bHgBIfi+6IKXPulCcN/nx03Xt8wYpbgvsbJjvyVQMwh4tQpFLMgTsghXax1jtOz6dPnNwGDDETyBp6vsEKWmS1H+bUJong81lKHy3bz8fNvicj4/fr6+MvP4FSDkKuJIcTi6woJTU3qpLoD/20gDeXR6pqGUNtrJOsZmCrqehX7r00ddrmgs3uYrmxg/vdtQbdOuYgBdR2Xt9kAMTR1T+Pfo++7fVaerhU9DVxu/LqWOIf+dFErx33ei7SLKTWSZcFIEUq1ax8aE3v3d18yhtIZ8zbtK9V0lXp6ptIhwxqYIEfmtTznuGO+KSwwcJ4IIYpI7V9jGUIDLwCpERbsoFgG9WgRqFdt5FXlalFwo788oddW1Sx5CMxNdfLSh1JDhS8m7Jc10kkPkWY7gZpcUBlaRUjsPGHfaaAxyp3BWrZ1XkadlkI8IU1Ghb6VT4wSxMdilXIb2BQl1eAoDG9N1iI3JBChLld+q3JAy1NqEGjCUT5sLsRvUEqm9RrtIvkvZRm2Ku2s873Dfm/MippPpTAiILUQuorxG1+gaPfOIGQxBKIrZKcFFeUaf67aY6V+Gj9g3v510U5YFlFYAgH3cU1twr08eqWX4awCGIIIUPrV7T2CAgf3rG4U4sGd/oZgZUFMXZo8leCH/vKvslDy71gP0eXfooEiNFF9TAv1pEUFtWzwzJA+fn9jzPkHHFOrMox5lnOT5XBTEZ/T21P4spEY4W3Ju3HXfd17fL6PN70/5rU+aPh2XGuC5Rr0pel5q54veZz9yv0CEPVpGV159xkUfA1w7gZkZWYbTF849kpPIngJlOva3hFEZC4roZzsmB30bd1l5tUE+N/9rlEy7rkvbILtv3FIoJd2ilWbG4YPXFfnGZPKUOlNe9M9y11veo2Xw05bnTnTUNUqj3ZhFifXtojNYQ6gfCmIQIWN+It8/mZ4WQkBKRu8z8PsIQNfinK4O7MqnC/Yv4iOG5oNDead2gO8OrJLFH5OfVatbX+o7ZpY1BkPkI8deAUOGEALrlJ3NxWT6KEEALDvvpRxMi/jarn+TsjCj76qrVOpr7cn7m0q7vB6AAHvDruVn8KKTUVhanXKGUKrQLxrDaE3XDBAQBLLp+mPitiM3Pp4LAkhfWdm1KWhZTC76fp/g4RDh9wN3oVmIMWZCdnNBElCda+cHVj8eaaf6YullNAqgnAg3Hjp4Srzg5jsey5GV4CWwYa5xGi0/7L62T4ng7zaPi1JX5PrjTSGkRvqHGpdlUlj+hGDwLQePPCy++HM+/8GNydoZxQsteqV7nZ5J012h+WKfllXX1uvGllUm6gMbeGb15yrQjlj+RiEMAOv59NwrXvzJHxWf+bKXfWy6NvmoPhlgZBzQMmJ6DSaCWqvQ7wjD0cn1z0PQf2kdumKQYsXY2RGiln/udG5KzGQXkSxpGV+fTj/2La993eNiQqI4sLbvQ6AMDJY7ruGTyvOnCiL5LJv3IYs1xiB2rszeDUpdnWloNxDLTpMfA0pajNPxfGeIkQlsrG98cJrlVwQTcMv1N/xlprcI7kDxaeVw9Mvq0Gp06ArSbmjJXaAY8gtNGe/KOGkKGzNzJjJcv/fAn85lCZFlOV78vOf92Xo+AVhmo88CdFGKL901nrqi82PTx5vQ957K/DjYXeq3SWimaBXIX9fDLNayHLffdut7iAhiez5b+9Zjf/f9eyfTp0H6xjkS408HGvK1YRIacFu2B1/XlMA12kkKxQV2dZyY2Jn9JkEQG9nkqTd87be/T0pJ4lf/4Fendz/n7icP7T30ZxAC0De27xj3oSKiwUtPxa6ixv14pWUajauRdrspwlPwDAIObuz/01d/8sue/q4f/66puHB5Q2ZEfOOhw78xmUzB7lXBRMvr2J3QL7vdCc8kMgMqNhZY9ltG/kyn1DhXKN3Chi0sXCwlZ1mOmw8ffuesmOO6A9eReNUnfqKUAD7z7pf/xt7JZA4go6vBrvoQK+STXaORSTf4NUu/OI25kQjQhlpEDbaW6XzvZH32ypd8xjskGHd/2jFJzCyICJMsl7d8xSv+18Onn3wlSUgGsoqpFQrqhNbbh7bVun7YNRqJEqZjr5GirrEXC2kN3eBD7WtkCChZQDz7+pve9cR/+6NXz8pC3Mv3kgDAR48eFfOywB1Hbn7rZJIRyxXqYEbQ/W9tOP39muyPTR8HQZcxqueuDQjNUAHxwdlrUZlBZN0L5JgZ00lOz73hprfOygI4elTcQ/eUxKy2fxARfvfd77712Bu//S9OXzx7iETObNcF8s76d0PW2sfeuaYFrlEfSp1sCln4PhNVC6PTDlfMyCsRCGCWMzqy/7qz7/jXb777U+/61McBEDMr1UFEjGMQX/TZn/PoHdff/MuU52DGCuH+DnqGG6VrNICGjAlfgGM7ImPC704B7tqY1IUTrIJgsKRJjttvuOk//61P+ozHjx49mhsOK+xw13Hems/wf3z65/7kvumeAlI6+mWHJzSXvrZ+CK0UM9fIJd9NHFv42gJ2fcsbjT/WMy+hZeKV8BDAkCwOrO2bfcnLj/5EUZZ41ateZY07MTMRqWM5jx07lv3Kf317+bzXvOreD53+2DEUsrTBQN5VtdZNIdbGklmztn2VgqHXqKJl9n1oA1hoZWpqeUODfG3UvveihKDsBTfc+taPvP13v/Y1X/M12cmTJ0sAYGbRiB7MZYlXf8qn/9CBtb1zZqblHRMUoaF6htBEDmPrLDPFMsY02E4sWV4lWubU4TKyNn0TW9kXGm8pebZ9H0RxBggApKT907XiS1/xmf+yZKa77rqrlriGAACFAt7+treVL/o7X/Bz9z/x0DdgLksmgwKWbAHH1OQDVg5HKahhRwiMjsljjIzg7eYiHV/4l8HL2G25jL5ZClKJGyRiLpGJ7MW3POfn//ptv/ONs9d8Vcb33isBFfczCCAzMwEAcNddd3HJTN/w+V92/MieA+cZkuzCoDEt4LJp1I4LmeqBQQofAu5IUxJ25SyFGDS9GlaWXg0rVVtkkQBmZrp+z4Fzb/jqb3rjrCwId93F6jVr8FkAkC4COHHihDx27Jh4wzd++yN33/7849P1NcHsmv4ltMrVAIXHtFo7UVezjNv0127obIajBJx/q97XzwBiyXKyNhWfdMfzfvgb7rnn4WPHjgmcOFGTdSJisxLQx/aEYxB8L/Pzv+pV73rg7OOfTSWqgODY6wKWFcTx/bZFWfYXXAwNjC4d+pPO2ylgzCBurzlso4CMK/JxHEgdu98jCIuAkiGz5x65+U8e+OXf+0wiKhEws8YFEMzs40PGXceZiOQ3f8mxb7xh76HzzNKJFYw8cv16jDWXOnowsGcmsXJ9hTQ6AtIKuib0I5vd5OycaOeYwh+b9ltlNDn6OoGQ8BOzLHF4776tez7787+ZiObHjh0LzVsA2gXgAAIATpyQx+49lv2T13/H3xx90Uu+fc/GmuByXlZR0EQl0CdmEIqyXqVEqdreH7yjklEEI1vdIX2zU0HIZY+bsQzTGMG/ALEsy7WN9ewVd770+/7F9/zA+44eP5q/7W1vK4M5aBcggxcHqNExZGu/PCk/5Wu/6F/86cMffMN8LgtCljN8CxPj0/h9LWn9wNgy5koXpoAiS6lTjP9Ys61MfVechs7Dj1VuUnkxwzuU3HhOEPoXYprlL37Wc37hr3/pd/7+1me+Isd99xWx3JhZdCsARdn6ZFreec/n/uIHHv/o1/KsLJgor+rWEhNw/ZSr2f8L+VtD/Oqu5NcUQDf5QtgrJrGT5Y0VfDLZtcz5MwrOkD/vxpvf9ZGT930REc2hDveJFm72AnCH8IOZ5dZ8Jt7/i+943Z033f7rNM1yMM9reJ0i/8bsGRvZXhFaxnTWqvqvq0L+4hz2Pi+L+gi/uy+faOlKnZgLpjK/47qbPvArP/DDryGi7ePHjye1SJI0EREfP34cRCQ/+NZ3/p0X3XTH74qcJmBZEDlKIPhvWeQqmV2kvuVfzbGNVQiwtbVdSrsOqYOvbIJp2sbjgkarzZgyCibOX3DLsx94+z/7N1/5kpd89tnjx49nb3zjG5NqGZsGDBMzQa0gOnDX//n5b/nwk498ebFdFJSJjGVL8zNUVGyMlXO2FKexd8W1cPyxIfVa6RhAS9vuxOpFW8ASp5p7BzE73utCpotMw0bzlnPKs8ltB4788S/+kx977ee+4hUPfvUv/VJ28p57gkG/YNa9FAAAMAikjhf/5Nd96Y9/6LEH/8Hm1jYImeQuVbeIoIY6QHkwOxdhHpOuFgUAqH5zle+yfW5g/L5ddmB5WQogeLMvMctS5muT7Pk33vqOP/rpe1973XXXnT9+773TE/fcM0vN2p4H0I8h8PHjxwURyfvf8hvf/hmfcPd3HNqzf86QAszRiONgctut0XGrgEkHEnl//c+GdqWKnuD5fuxOKCkeWbHvhFfaSkOE31nJWWVTsixpz5492ac8+wU/8cH/8ltfet11150/duxY9sZjx+busv7O7FtWAnYSMxPdQwInUX7bie8/+mt/9r/e/LHzp18g5wUTZfUzBWsvDkQBKzk1uIO0Y9DbIWMfVn0reCotc1t3a8A7RZlp1OWc5FN/SpJlychEdsP+Q2c+/QUv/ofv/PFf+E9zWQowMzoC+dFSjQLwdwUm09GjOe67r3j44Yev+4p/+m1v+shjD3/bha1NAlNJJIhJ6mtH3Qp1FBNqrLEEYDcEaQy6pgAWJ9+tGNuV8ZVAaru1Te+BmFmWgMw31tdxx3U3/vfXfe6Xfff3/4N/9ACOIud3cTlIbk3+CysAADh2LMPJk+WEMnz9D3z357zr/X/8g4+dP3t0a7YFgCVIMJjCiCBI3Pxo/U9udhzpgFEK94sIEoVw8FUag0gh1yI9E2jpCsB41IljojaD5j0CpNqEJ/N8MsFN+w4++PIX3vWmd/74W39+a75tZW5hloe6AD5pBSIAlMxMX/Ldr3vt/R/9yPc+eeHsJ2/OZ0AJgKggItEZLOxmGuxKO4mdsVKxkMnVvMDp44rGXpnn5W0VZkoZzSlD/bYESwIg8ukE16/vfeJFtz/3p971M/f+dC6y0yVLcfz4cZw4cWKUQTeaAjB07Nix7OTJkxIAM/P6V33P67/qLx748DefunDucy/LGcn5HAAYJEpSioB4FD2cqHWHIoAGvIOe2nQz3SHaiSh8rFzEynYQkZ1C9F9MoJ08wGTUduxQAMFovgrxKqFnAjhDBmxMpji8se+vPvHW573lZ//xj/z8nc97/hMFM77lW14/efOb3zwfi2NgCQrA0jFkOIkSADama/j7P/y9n/bu97/3nifOnf6Ki1tX7rxSzCDnhYH0EkQSRCbePEApdCiARX3oRgfuAvR36zDm4O1qG3e1HWJpRcv7icOr1sZLat9lxVJiW8V1nYywA2BWG2kIzBkEgExgLc9xYLpx5vp9B377U++86+RbfvgnflMQXSIS+JTXf/PkS2+5pRzL6lcsMpHeCty5HHgwKV+FAUjtH6x/3T/5h5/1lw9/+AvPXrr4qotXLt+1LYs927JEKUuglIC5mETxxACpwwntoK87T9YdWHRzDnkCbl6gUJpdVgA7mW9M2fiWnhhh787tnwjtpILtUp4NBOO/7CbVQ1DXmw3T1R2bBECoYQxAEIgyTLMM6yKX+9b2fuiGAwfefdsNN//Wd3z1a3/vKz/vyx+ZFwX+M5fZj37rt4o/+ZmfkXo//+hkNgPl0JsG9Dlh1Vq7MZXCcQjcDzKogACsTdfwpp/6sTveff97P+nhM6deevbypZdubm/eubm9ffv2fH6ogMwKlpDM4FJqK+QoCMmA0NCrK2DVZr3MMxGKxvqmLxCgDI2U0CAby2ovkk/j3QDkTuXbtXpW+RrfNvCSneLSn11BCy2h9RcgheoS4rdiEBEprr9vkqbsXTFoxqxTYCPYui2EinWTEBBEyIiQQWCaZRc31qdPrE0mD1y/ceADN19345+/7EV3/fmbvv37/iYnsV1qZr7z337n2vufvq6878SJEsqNHh6c7yCDANYAzMwhgV4LqK4ZUwMx6Ng9x8TJUycJ96G2cGhCAjNZZv/lN3/lWe96zx88+4mLZ+946ty551y6cOmWbSGfdfHKpf0TEtdnIj9yeba1lwjXbc63aTafYXs+h5R6tAQUAdUitA5qMFQ7IFnlY/c5OOOIZXULLgFgd+CadI7yp5owsGMYnHfMh5BgAmggm9hwaPScBp82G/9FqoSxkZd6VoU5GESkk7LjhjjK18RFSL1IEFY+6qwbwdZReamz0G3pDne2ULpe9xovoXZwlYpOp97RS1mdzEw/1wCmTlsj/T0jwiSfYJrn2DNdA0t5fppl59em65cvbW89dt2+A5cE+NGNydrp62848titB697+MWfcPeD3/113/TkvvU950pZQkqJkhnveeQ9e/77O/9CXnfTBf6sGz9LvvzlLzeFGrjvq8BktO7Jc/Dcj/8fkizMrqmGzz0AAAAASUVORK5CYII="


def app_icon():
    pm = QPixmap()
    pm.loadFromData(base64.b64decode(APP_ICON_B64))
    return QIcon(pm)


# ----------------------------------------------------------------------------
# مدل داده
# ----------------------------------------------------------------------------

@dataclass
class Server:
    name: str
    host: str = ""
    port: int = DEFAULT_RTMP_PORT
    region: str = REGION_UNKNOWN
    note: str = ""
    id: str = field(default_factory=lambda: uuid4short())


def uuid4short():
    import uuid as _uuid
    return _uuid.uuid4().hex[:8]


def server_rtmp_url(s):
    if isinstance(s, dict):
        host, port = s.get("host", ""), s.get("port", DEFAULT_RTMP_PORT)
    else:
        host, port = s.host, s.port
    if not host:
        return ""
    return f"rtmp://{host}:{port}/live"


# ----------------------------------------------------------------------------
# تشخیص خودکار نام و منطقه از روی هاست
# ----------------------------------------------------------------------------

def suggest_name(host: str) -> str:
    """نام پیشنهادی از روی هاست؛ مثلاً ir1.example.com -> IR1"""
    host = (host or "").strip().lower()
    if not host:
        return ""
    if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", host):
        return T("server_word") + " " + host
    label = host.split(".")[0]
    label = re.sub(r"[-_]+", " ", label).strip()
    return label.upper() if label else host


_REGION_RULES = [
    ("ir", ("ir",), ("iran", "tehran", "shiraz", "tabriz", "mashhad",
                      "isfahan", "karaj", "ahvaz", "qom", "ika", "thr")),
    ("de", ("de",), ("germany", "berlin", "frankfurt", "munich", "nuremberg",
                      "falkenstein", "fra")),
    ("fr", ("fr",), ("france", "paris", "marseille", "roubaix", "gravelines",
                      "par", "cdg")),
    ("nl", ("nl",), ("netherlands", "amsterdam", "rotterdam", "ams")),
    ("uk", ("uk",), ("england", "london", "manchester", "lhr", "lon")),
    ("tr", ("tr",), ("turkey", "istanbul", "ankara", "ist")),
    ("ae", ("ae",), ("uae", "dubai", "emirates", "dxb")),
]


def detect_region(host: str) -> str:
    """حدس منطقه از روی هاست (کد کشور، TLD، نام شهر یا کد فرودگاهی)."""
    h = (host or "").strip().lower()
    if not h:
        return REGION_UNKNOWN
    tokens = [t for t in re.split(r"[.\-_]", h) if t]
    tld = tokens[-1] if tokens else ""
    for region, tlds, words in _REGION_RULES:
        if tld in tlds:
            return region
        for tok in tokens:
            if tok in words:
                return region
            m = re.fullmatch(r"(ir|de|fr|nl|uk|tr|ae)(\d+)?", tok)
            if m and m.group(1) in tlds:
                return region
            for w in words:
                if len(w) >= 3 and re.fullmatch(w + r"\d*", tok):
                    return region
        for w in words:
            if len(w) >= 3 and w in h:
                return region
    return REGION_UNKNOWN


def parse_rtmp(text):
    """برگرداندن (host, port) از یک RTMP URL یا host تنها."""
    text = (text or "").strip()
    if not text:
        return "", DEFAULT_RTMP_PORT
    if "://" not in text:
        text = "rtmp://" + text
    try:
        u = urlparse(text)
        host = u.hostname or ""
        port = u.port or DEFAULT_RTMP_PORT
        return host, port
    except Exception:
        return "", DEFAULT_RTMP_PORT


# ----------------------------------------------------------------------------
# تست شبکه — بدون باز شدن پنجره CMD، همه سرورها موازی
# ----------------------------------------------------------------------------

def _popen_kwargs():
    """روی ویندوز پنجره کنسول باز نشود."""
    if sys.platform == "win32":
        si = subprocess.STARTUPINFO()
        si.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        return {"startupinfo": si, "creationflags": subprocess.CREATE_NO_WINDOW}
    return {}


def ping_host(host, count=2, timeout_ms=1500):
    """میانگین پینگ (ms) و درصد packet loss. بدون نمایش پنجره."""
    if not host:
        return None, 100.0
    system = platform.system().lower()
    if system == "windows":
        cmd = ["ping", "-n", str(count), "-w", str(timeout_ms), host]
    else:
        cmd = ["ping", "-c", str(count), "-W", str(max(1, timeout_ms // 1000)), host]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              timeout=count * (timeout_ms / 1000) + 5,
                              **_popen_kwargs())
        out = proc.stdout or ""
        times = [float(x) for x in re.findall(r"time[=<](\d+(?:\.\d+)?)\s*ms", out)]
        loss_m = re.search(r"(\d+)%\s*(?:packet\s*)?loss", out, re.IGNORECASE)
        if not loss_m:
            loss_m = re.search(r"Lost\s*=\s*\d+\s*\((\d+)%", out)
        loss = float(loss_m.group(1)) if loss_m else (0.0 if times else 100.0)
        avg = sum(times) / len(times) if times else None
        return avg, loss
    except Exception:
        return None, 100.0


def tcp_probe(host, port, timeout=3.0):
    """زمان برقراری اتصال TCP به پورت RTMP (ms) یا None."""
    if not host:
        return None
    try:
        t0 = time.perf_counter()
        with socket.create_connection((host, int(port)), timeout=timeout):
            pass
        return (time.perf_counter() - t0) * 1000.0
    except Exception:
        return None


def probe_server(server):
    """تست کامل یک سرور؛ نتیجه دیکشنری."""
    s = dict(server)
    ping_ms, loss = ping_host(s.get("host", ""))
    tcp_ms = tcp_probe(s.get("host", ""), s.get("port", DEFAULT_RTMP_PORT))
    ok = tcp_ms is not None
    if not ok:
        score = 1_000_000.0
    else:
        base = tcp_ms if tcp_ms is not None else 9999.0
        score = base + (ping_ms or 500.0) * 0.3 + loss * 20.0
    return {
        "id": s.get("id"), "name": s.get("name"), "region": s.get("region"),
        "host": s.get("host"), "port": s.get("port"),
        "ping_ms": ping_ms, "loss": loss, "tcp_ms": tcp_ms,
        "ok": ok, "score": score,
    }


class ScanThread(QThread):
    """اسکن موازی همه سرورها؛ نتیجه هر سرور جدا emit می‌شود."""
    one_done = Signal(int, dict)   # index, result
    all_done = Signal(list)

    def __init__(self, servers, parent=None):
        super().__init__(parent)
        self.servers = servers

    def run(self):
        results = [None] * len(self.servers)
        if not self.servers:
            self.all_done.emit([])
            return
        with ThreadPoolExecutor(max_workers=min(32, len(self.servers))) as ex:
            futs = {ex.submit(probe_server, s): i for i, s in enumerate(self.servers)}
            for fut in as_completed(futs):
                i = futs[fut]
                try:
                    res = fut.result()
                except Exception:
                    res = {"id": self.servers[i].get("id"), "ok": False,
                           "ping_ms": None, "loss": 100.0, "tcp_ms": None,
                           "score": 1_000_000.0, "name": self.servers[i].get("name"),
                           "region": self.servers[i].get("region"),
                           "host": self.servers[i].get("host"),
                           "port": self.servers[i].get("port")}
                results[i] = res
                self.one_done.emit(i, res)
        self.all_done.emit(results)
# ----------------------------------------------------------------------------
# تم‌ها — پالت رنگی + قالب QSS
# ----------------------------------------------------------------------------

QSS_TEMPLATE = Template("""
QMainWindow, QWidget { background-color: $bg; color: $text; }
QLabel#title { font-size: 22px; font-weight: bold; color: $accent; }
QLabel#subtitle { font-size: 12px; color: $subtext; }
QLabel#banner { font-size: 14px; font-weight: bold; color: $on_accent;
    background-color: $accent; border-radius: 8px; padding: 8px; }
QPushButton { background-color: $accent_deep; color: $btn_text; border: none;
    border-radius: 8px; padding: 9px 14px; font-size: 13px; font-weight: bold; }
QPushButton:hover { background-color: $accent_hover; }
QPushButton:disabled { background-color: $disabled_bg; color: $disabled_text; }
QPushButton#danger { background-color: $danger; color: #ffffff; }
QPushButton#danger:hover { background-color: $danger_hover; }
QPushButton#ghost { background-color: $ghost_bg; color: $ghost_text; }
QPushButton#ghost:hover { background-color: $ghost_hover; }
QLineEdit, QTextEdit, QComboBox { background-color: $input_bg; color: $text;
    border: 1px solid $input_border; border-radius: 6px; padding: 7px; font-size: 13px; }
QTableWidget { background-color: $surface; gridline-color: $table_grid;
    border: 1px solid $table_border; border-radius: 8px; font-size: 13px; }
QTableWidget::item { padding: 6px; }
QHeaderView::section { background-color: $accent_deep; color: $btn_text;
    padding: 8px; font-weight: bold; border: none; }
QProgressBar { border: 1px solid $input_border; border-radius: 6px; background: $progress_bg;
    text-align: center; color: $text; height: 18px; }
QProgressBar::chunk { background-color: $accent; border-radius: 5px; }
QDialog { background-color: $bg; }
QCheckBox { font-size: 13px; }
""")

THEME_PALETTES = {
    "dark": dict(
        bg="#0d1218", surface="#131a22", text="#e9f2ec", subtext="#9aa7ad",
        accent="#00e676", accent_deep="#1b5e20", accent_hover="#2e9e44",
        on_accent="#0d1218", btn_text="#ffffff",
        disabled_bg="#37474f", disabled_text="#8fa0a8",
        danger="#c62828", danger_hover="#e53935",
        ghost_bg="#1c2830", ghost_hover="#2a3842", ghost_text="#e9f2ec",
        input_bg="#161e26", input_border="#2f3d47",
        table_grid="#222e38", table_border="#222e38", progress_bg="#161e26"),
    "light": dict(
        bg="#f4f6f4", surface="#ffffff", text="#1b2b1e", subtext="#6b7a6e",
        accent="#1b7a2e", accent_deep="#1b7a2e", accent_hover="#239a3a",
        on_accent="#ffffff", btn_text="#ffffff",
        disabled_bg="#b9c6bb", disabled_text="#6b7a6e",
        danger="#c62828", danger_hover="#e53935",
        ghost_bg="#dde5de", ghost_hover="#cdd8ce", ghost_text="#1b2b1e",
        input_bg="#ffffff", input_border="#b9c6bb",
        table_grid="#dde5de", table_border="#cdd8ce", progress_bg="#e7ede7"),
    "midnight": dict(
        bg="#0a0f1e", surface="#101a30", text="#e3ecff", subtext="#8b9bb8",
        accent="#38bdf8", accent_deep="#0369a1", accent_hover="#0ea5e9",
        on_accent="#04121f", btn_text="#ffffff",
        disabled_bg="#1c2742", disabled_text="#5b6b8c",
        danger="#b91c1c", danger_hover="#dc2626",
        ghost_bg="#16213a", ghost_hover="#1e2c4d", ghost_text="#e3ecff",
        input_bg="#0e1628", input_border="#24345a",
        table_grid="#1e2c4d", table_border="#1e2c4d", progress_bg="#0e1628"),
    "emerald": dict(
        bg="#0b1512", surface="#10201a", text="#e6f4ec", subtext="#93a89d",
        accent="#34d399", accent_deep="#047857", accent_hover="#10b981",
        on_accent="#06281c", btn_text="#ffffff",
        disabled_bg="#1a2b23", disabled_text="#5f7a6d",
        danger="#b91c1c", danger_hover="#dc2626",
        ghost_bg="#14271f", ghost_hover="#1d352b", ghost_text="#e6f4ec",
        input_bg="#0e1c15", input_border="#234034",
        table_grid="#1d352b", table_border="#1d352b", progress_bg="#0e1c15"),
    "sunset": dict(
        bg="#171008", surface="#221709", text="#f7ead9", subtext="#a89880",
        accent="#fb923c", accent_deep="#c2410c", accent_hover="#f97316",
        on_accent="#241102", btn_text="#ffffff",
        disabled_bg="#2a2013", disabled_text="#7a6a52",
        danger="#b91c1c", danger_hover="#dc2626",
        ghost_bg="#2a1e10", ghost_hover="#3a2a15", ghost_text="#f7ead9",
        input_bg="#1e1509", input_border="#453419",
        table_grid="#3a2a15", table_border="#3a2a15", progress_bg="#1e1509"),
    "amethyst": dict(
        bg="#120e1c", surface="#1a1428", text="#ece5f7", subtext="#9a8fb5",
        accent="#c084fc", accent_deep="#7e22ce", accent_hover="#a855f7",
        on_accent="#1e0a33", btn_text="#ffffff",
        disabled_bg="#221b36", disabled_text="#6f6390",
        danger="#b91c1c", danger_hover="#dc2626",
        ghost_bg="#1f1832", ghost_hover="#2c2342", ghost_text="#ece5f7",
        input_bg="#161129", input_border="#352a52",
        table_grid="#2c2342", table_border="#2c2342", progress_bg="#161129"),
    "ocean": dict(
        bg="#e9f3f9", surface="#ffffff", text="#0c2b3e", subtext="#5b7a90",
        accent="#0284c7", accent_deep="#0369a1", accent_hover="#0ea5e9",
        on_accent="#ffffff", btn_text="#ffffff",
        disabled_bg="#c3d5e0", disabled_text="#6b8a9c",
        danger="#c62828", danger_hover="#e53935",
        ghost_bg="#d5e8f2", ghost_hover="#bfdcee", ghost_text="#0c2b3e",
        input_bg="#ffffff", input_border="#aecadd",
        table_grid="#d5e8f2", table_border="#bfd9e8", progress_bg="#d9eaf4"),
    "rose": dict(
        bg="#fbf0f4", surface="#ffffff", text="#3d1220", subtext="#96707e",
        accent="#db2777", accent_deep="#be185d", accent_hover="#ec4899",
        on_accent="#ffffff", btn_text="#ffffff",
        disabled_bg="#e8ccd5", disabled_text="#9c7585",
        danger="#c62828", danger_hover="#e53935",
        ghost_bg="#f5dde6", ghost_hover="#eec9d8", ghost_text="#3d1220",
        input_bg="#ffffff", input_border="#e5b9cb",
        table_grid="#f5dde6", table_border="#e8c3d2", progress_bg="#f7e0e9"),
}

# کلید تم -> کلید رشته نمایشی (دوزبانه)
THEMES = {"dark": "theme_dark", "light": "theme_light",
          "midnight": "theme_midnight", "emerald": "theme_emerald",
          "sunset": "theme_sunset", "amethyst": "theme_amethyst",
          "ocean": "theme_ocean", "rose": "theme_rose",
          "system": "theme_system"}


def resolve_theme(theme):
    if theme == "system":
        try:
            hints = QApplication.instance().styleHints()
            scheme = hints.colorScheme()
            from PySide6.QtCore import Qt as _Qt
            return "dark" if scheme == _Qt.ColorScheme.Dark else "light"
        except Exception:
            return "light"
    return theme if theme in THEME_PALETTES else "dark"


def apply_theme(theme):
    app = QApplication.instance()
    if app is None:
        return
    app.setStyleSheet(QSS_TEMPLATE.substitute(THEME_PALETTES[resolve_theme(theme)]))




# ----------------------------------------------------------------------------
# بررسی آپدیت از گیت‌هاب
# ----------------------------------------------------------------------------

def _ver_tuple(v):
    return tuple(int(x) for x in re.findall(r"\d+", str(v))[:3])


def fetch_latest_release():
    req = urllib.request.Request(
        UPDATE_API,
        headers={"User-Agent": "StreamScanner",
                 "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.load(r)


def find_setup_asset(release):
    for a in release.get("assets", []):
        name = (a.get("name") or "").lower()
        if name.endswith("setup.exe"):
            return a
    return None


def find_portable_asset(release):
    for a in release.get("assets", []):
        name = (a.get("name") or "").lower()
        if "portable" in name and name.endswith(".exe"):
            return a
    return None


# ----------------------------------------------------------------------------
# دیالوگ افزودن / ویرایش سرور
# ----------------------------------------------------------------------------

class ServerDialog(QDialog):
    def __init__(self, parent=None, server=None):
        super().__init__(parent)
        self.setWindowTitle(T("add_server") if server is None else T("edit_server"))
        self.setMinimumWidth(430)
        self._name_touched = server is not None

        layout = QFormLayout(self)
        layout.setSpacing(10)

        self.name_edit = QLineEdit(server.name if server else "")
        self.name_edit.setPlaceholderText(T("ex_name"))
        self.name_edit.textEdited.connect(lambda _t: setattr(self, "_name_touched", True))

        self.url_edit = QLineEdit()
        if server:
            self.url_edit.setText(server_rtmp_url(server))
        self.url_edit.setPlaceholderText("rtmp://host:1935/live")
        self.url_edit.setLayoutDirection(Qt.LeftToRight)
        self.url_edit.textChanged.connect(self.on_url_changed)

        self.region_combo = QComboBox()
        for _rk in REGIONS:
            self.region_combo.addItem(region_name(_rk), _rk)
        if server:
            _skey = server.region if server.region in REGIONS \
                else _REGION_FA2KEY.get(server.region, REGION_UNKNOWN)
            idx = self.region_combo.findData(_skey)
            self.region_combo.setCurrentIndex(idx if idx >= 0 else REGIONS.index(REGION_UNKNOWN))

        self.note_edit = QLineEdit(server.note if server else "")
        self.note_edit.setPlaceholderText(T("optional_note"))

        hint = QLabel(T("auto_hint"))
        hint.setStyleSheet("color: #9e9e9e; font-size: 11px;")
        hint.setWordWrap(True)

        layout.addRow(T("server_name"), self.name_edit)
        layout.addRow(T("rtmp_addr"), self.url_edit)
        layout.addRow(T("region"), self.region_combo)
        layout.addRow(T("note"), self.note_edit)
        layout.addRow(hint)

        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.button(QDialogButtonBox.Ok).setText(T("ok"))
        buttons.button(QDialogButtonBox.Cancel).setText(T("cancel"))
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addRow(buttons)

    def on_url_changed(self, text):
        host, _port = parse_rtmp(text)
        if not host:
            return
        if not self._name_touched:
            self.name_edit.setText(suggest_name(host))
        region = detect_region(host)
        if region != REGION_UNKNOWN:
            idx = self.region_combo.findData(region)
            if idx >= 0:
                self.region_combo.setCurrentIndex(idx)

    def get_server(self, existing=None):
        host, port = parse_rtmp(self.url_edit.text())
        name = self.name_edit.text().strip() or suggest_name(host) or T("server_word")
        region = self.region_combo.currentData()
        note = self.note_edit.text().strip()
        if existing:
            existing.name, existing.host, existing.port = name, host, port
            existing.region, existing.note = region, note
            return existing
        return Server(name=name, host=host, port=port, region=region, note=note)


class ImportDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle(T("import_title"))
        self.setMinimumSize(480, 320)
        layout = QVBoxLayout(self)
        hint = QLabel(T("import_hint"))
        hint.setStyleSheet("color: #9e9e9e; font-size: 12px;")
        hint.setWordWrap(True)
        self.text = QTextEdit()
        self.text.setPlaceholderText("IR1 | rtmp://ir1.example.com:1935/live\nDE1 | rtmp://de1.example.com:1935/live")
        self.text.setLayoutDirection(Qt.LeftToRight)
        layout.addWidget(hint)
        layout.addWidget(self.text)
        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.button(QDialogButtonBox.Ok).setText(T("do_import"))
        buttons.button(QDialogButtonBox.Cancel).setText(T("cancel"))
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

    def get_servers(self):
        out = []
        for line in self.text.toPlainText().splitlines():
            line = line.strip()
            if not line or "|" not in line:
                continue
            name, url = [p.strip() for p in line.split("|", 1)]
            host, port = parse_rtmp(url)
            if not host:
                continue
            region = detect_region(host)
            out.append(Server(name=name or suggest_name(host), host=host,
                              port=port, region=region))
        return out


# ----------------------------------------------------------------------------
# دیالوگ تنظیمات
# ----------------------------------------------------------------------------

class SettingsDialog(QDialog):
    def __init__(self, parent, theme, auto_check):
        super().__init__(parent)
        self.setWindowTitle(T("settings"))
        self.setMinimumWidth(420)
        layout = QVBoxLayout(self)
        layout.setSpacing(12)

        form = QFormLayout()
        self.theme_combo = QComboBox()
        for _tk, _sk in THEMES.items():
            self.theme_combo.addItem(T(_sk), _tk)
        idx = self.theme_combo.findData(theme)
        self.theme_combo.setCurrentIndex(idx if idx >= 0 else 0)
        # پیش‌نمایش لحظه‌ای تم
        self.theme_combo.currentIndexChanged.connect(self._preview_theme)
        form.addRow(T("theme_label"), self.theme_combo)

        self.auto_check_box = QCheckBox(T("autocheck"))
        self.auto_check_box.setChecked(auto_check)
        form.addRow(self.auto_check_box)
        layout.addLayout(form)

        upd_box = QVBoxLayout()
        ver_label = QLabel(f"{T('current_version')} <b>{__version__}</b>")
        self.upd_status = QLabel("")
        self.upd_status.setWordWrap(True)
        self.upd_status.setStyleSheet("font-size: 12px; color: #9e9e9e;")
        check_btn = QPushButton(T("check_update"))
        check_btn.setObjectName("ghost")
        check_btn.clicked.connect(self.on_check_update)
        upd_box.addWidget(ver_label)
        upd_box.addWidget(check_btn)
        upd_box.addWidget(self.upd_status)
        layout.addLayout(upd_box)

        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.button(QDialogButtonBox.Ok).setText(T("save"))
        buttons.button(QDialogButtonBox.Cancel).setText(T("cancel"))
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

    def _preview_theme(self):
        parent = self.parent()
        if parent and hasattr(parent, "preview_theme"):
            parent.preview_theme(self.theme_combo.currentData())

    def on_check_update(self):
        self.upd_status.setText(T("checking"))
        parent = self.parent()
        if parent and hasattr(parent, "check_for_updates"):
            parent.check_for_updates(manual=True, status_label=self.upd_status)

    def values(self):
        return (self.theme_combo.currentData(),
                self.auto_check_box.isChecked())


# ----------------------------------------------------------------------------
# دیالوگ آپدیت جدید
# ----------------------------------------------------------------------------

class UpdateDialog(QDialog):
    """دیالوگ نسخه جدید: انتخاب بین فایل آپدیت (قابل‌حمل) و فایل نصبی."""
    def __init__(self, parent, release):
        super().__init__(parent)
        tag = release.get("tag_name", "")
        self.choice = None
        self.setWindowTitle(T("new_version_title"))
        self.setMinimumSize(460, 360)
        layout = QVBoxLayout(self)
        title = QLabel(f"{T('new_version')} <b>{tag}</b> {T('version_released')} "
                       f"({T('your_version')} {__version__})")
        title.setWordWrap(True)
        body = QTextEdit()
        body.setReadOnly(True)
        body.setPlainText(release.get("body") or "—")
        layout.addWidget(title)
        layout.addWidget(QLabel(T("changes")))
        layout.addWidget(body)
        row = QHBoxLayout()
        upd_btn = QPushButton(T("dl_update_file"))
        inst_btn = QPushButton(T("dl_installer"))
        later_btn = QPushButton(T("later"))
        later_btn.setObjectName("ghost")
        upd_btn.clicked.connect(lambda: self._done("portable"))
        inst_btn.clicked.connect(lambda: self._done("setup"))
        later_btn.clicked.connect(self.reject)
        row.addWidget(upd_btn)
        row.addWidget(inst_btn)
        row.addWidget(later_btn)
        layout.addLayout(row)
        self.release = release

    def _done(self, choice):
        self.choice = choice
        self.accept()


# ----------------------------------------------------------------------------
# پنجره اصلی
# ----------------------------------------------------------------------------

class MainWindow(QMainWindow):
    update_found = Signal(dict)

    def __init__(self):
        super().__init__()
        self.setWindowTitle(f"{APP_NAME} v{__version__}")
        self.resize(880, 620)
        self.servers = []
        self.theme = "dark"
        self.auto_check_update = True
        self.scan_thread = None
        self.last_results = {}
        self.update_found.connect(self.on_update_found)
        self.load_settings()
        apply_theme(self.theme)
        self.build_ui()
        self.refresh_table()
        if self.auto_check_update:
            QTimer.singleShot(2500, lambda: self.check_for_updates(manual=False))

    # -- ذخیره‌سازی ---------------------------------------------------------
    def load_settings(self):
        try:
            data = json.loads(DATA_FILE.read_text(encoding="utf-8"))
            items = data.get("servers", []) if isinstance(data, dict) else data
            self.servers = [Server(**{k: v for k, v in s.items()
                                      if k in Server.__dataclass_fields__})
                            for s in items]
            if isinstance(data, dict):
                self.theme = data.get("theme", "dark")
                self.auto_check_update = data.get("auto_check_update", True)
            # مهاجرت نام‌های فارسی قدیم منطقه به کلید جدید
            for _sv in self.servers:
                if _sv.region in _REGION_FA2KEY:
                    _sv.region = _REGION_FA2KEY[_sv.region]
                elif _sv.region not in REGIONS:
                    _sv.region = REGION_UNKNOWN
        except Exception:
            self.servers = [Server(**s) for s in DEFAULT_SERVERS]

    def save_settings(self):
        try:
            DATA_FILE.write_text(json.dumps(
                {"servers": [asdict(s) for s in self.servers],
                 "theme": self.theme,
                 "auto_check_update": self.auto_check_update},
                ensure_ascii=False, indent=2), encoding="utf-8")
        except Exception:
            pass

    # -- رابط ---------------------------------------------------------------
    def build_ui(self):
        central = QWidget()
        self.setCentralWidget(central)
        layout = QVBoxLayout(central)
        layout.setSpacing(10)
        layout.setContentsMargins(16, 16, 16, 16)

        title = QLabel(APP_NAME)
        title.setObjectName("title")
        title.setAlignment(Qt.AlignCenter)
        subtitle = QLabel(T("subtitle"))
        subtitle.setObjectName("subtitle")
        subtitle.setAlignment(Qt.AlignCenter)
        layout.addWidget(title)
        layout.addWidget(subtitle)

        self.banner = QLabel("")
        self.banner.setObjectName("banner")
        self.banner.setAlignment(Qt.AlignCenter)
        self.banner.setVisible(False)
        layout.addWidget(self.banner)

        btn_row = QHBoxLayout()
        self.scan_btn = QPushButton(T("scan_all"))
        self.scan_btn.clicked.connect(self.run_scan)
        add_btn = QPushButton(T("add"))
        add_btn.setObjectName("ghost")
        add_btn.clicked.connect(self.add_server)
        edit_btn = QPushButton(T("edit"))
        edit_btn.setObjectName("ghost")
        edit_btn.clicked.connect(self.edit_server)
        del_btn = QPushButton(T("delete"))
        del_btn.setObjectName("danger")
        del_btn.clicked.connect(self.delete_server)
        import_btn = QPushButton(T("bulk_import"))
        import_btn.setObjectName("ghost")
        import_btn.clicked.connect(self.import_servers)
        settings_btn = QPushButton(T("settings"))
        settings_btn.setObjectName("ghost")
        settings_btn.clicked.connect(self.open_settings)
        for b in (self.scan_btn, add_btn, edit_btn, del_btn, import_btn, settings_btn):
            btn_row.addWidget(b)
        layout.addLayout(btn_row)

        self.progress = QProgressBar()
        self.progress.setVisible(False)
        layout.addWidget(self.progress)

        self.table = QTableWidget(0, 6)
        self.table.setHorizontalHeaderLabels(
            [T("col_server"), T("col_region"), T("col_ping"), "Packet Loss",
             T("col_tcp"), T("col_status")])
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table.itemDoubleClicked.connect(self.copy_row_server)
        layout.addWidget(self.table)

        bottom = QHBoxLayout()
        self.copy_btn = QPushButton(T("copy_best"))
        self.copy_btn.clicked.connect(self.copy_best)
        self.copy_btn.setEnabled(False)
        bottom.addWidget(self.copy_btn)
        layout.addLayout(bottom)

    # -- جدول ----------------------------------------------------------------
    def refresh_table(self):
        self.table.setRowCount(len(self.servers))
        for i, s in enumerate(self.servers):
            self.table.setItem(i, 0, QTableWidgetItem(s.name))
            self.table.setItem(i, 1, QTableWidgetItem(region_name(s.region)))
            r = self.last_results.get(s.id)
            if r:
                self.fill_result_row(i, r)
            else:
                for c in range(2, 6):
                    self.table.setItem(i, c, QTableWidgetItem("—"))

    def fill_result_row(self, i, r):
        ping_txt = f"{r['ping_ms']:.0f} ms" if r["ping_ms"] is not None else T("failed")
        tcp_txt = f"{r['tcp_ms']:.0f} ms" if r["tcp_ms"] is not None else T("down")
        ok_txt = T("up") if r["ok"] else T("down_emoji")
        self.table.setItem(i, 2, QTableWidgetItem(ping_txt))
        self.table.setItem(i, 3, QTableWidgetItem(f"{r['loss']:.0f}%"))
        self.table.setItem(i, 4, QTableWidgetItem(tcp_txt))
        item = QTableWidgetItem(ok_txt)
        item.setForeground(QColor("#00e676") if r["ok"] else QColor("#ff5252"))
        self.table.setItem(i, 5, item)

    # -- اسکن -----------------------------------------------------------------
    def run_scan(self):
        if self.scan_thread and self.scan_thread.isRunning():
            return
        if not self.servers:
            QMessageBox.information(self, T("scan"), T("add_first"))
            return
        self.scan_btn.setEnabled(False)
        self.copy_btn.setEnabled(False)
        self.banner.setVisible(False)
        self.progress.setVisible(True)
        self.progress.setMaximum(len(self.servers))
        self.progress.setValue(0)
        self._done_count = 0
        snapshot = [asdict(s) for s in self.servers]
        self.scan_thread = ScanThread(snapshot, self)
        self.scan_thread.one_done.connect(self.on_one_done)
        self.scan_thread.all_done.connect(self.on_all_done)
        self.scan_thread.start()

    @Slot(int, dict)
    def on_one_done(self, index, result):
        srv = next((s for s in self.servers if s.id == result.get("id")), None)
        if srv is None or index >= len(self.servers):
            return
        self.last_results[srv.id] = result
        self.table.setItem(index, 0, QTableWidgetItem(srv.name))
        self.table.setItem(index, 1, QTableWidgetItem(region_name(srv.region)))
        self.fill_result_row(index, result)
        self._done_count += 1
        self.progress.setValue(self._done_count)

    @Slot(list)
    def on_all_done(self, results):
        self.scan_thread = None
        self.scan_btn.setEnabled(True)
        self.progress.setVisible(False)
        ok_results = [r for r in results if r.get("ok")]
        if not ok_results:
            QMessageBox.warning(self, T("scan"), T("no_server"))
            return
        best = min(ok_results, key=lambda r: r["score"])
        srv = next((s for s in self.servers if s.id == best["id"]), None)
        name = srv.name if srv else best["name"]
        region = srv.region if srv else best.get("region", "")
        self.banner.setText(
            f"🏆 {T('best_server_lbl')}: {name} ({region_name(region)}) — "
            f"{T('col_ping')} {best['ping_ms']:.0f}ms، {T('col_tcp')} {best['tcp_ms']:.0f}ms")
        self.banner.setVisible(True)
        self.copy_btn.setEnabled(True)
        self._best = best

    def copy_best(self):
        best = getattr(self, "_best", None)
        if not best:
            return
        url = f"rtmp://{best['host']}:{best['port']}/live"
        QApplication.clipboard().setText(url)
        QMessageBox.information(self, T("copied"),
                                f"{T('rtmp_copied')}\n{url}\n\n"
                                f"{T('copied_msg')}")

    def copy_row_server(self, item):
        """دابل‌کلیک روی هر ردیف = کپی آدرس RTMP همان سرور."""
        row = item.row()
        if 0 <= row < len(self.servers):
            url = server_rtmp_url(self.servers[row])
            if url:
                QApplication.clipboard().setText(url)
                self.statusBar().showMessage(T("dblclick_copied"), 2500)

    # -- مدیریت سرورها ----------------------------------------------------------
    def selected_server(self):
        rows = self.table.selectionModel().selectedRows()
        if not rows:
            QMessageBox.information(self, T("select"), T("select_first"))
            return None
        return self.servers[rows[0].row()]

    def add_server(self):
        dlg = ServerDialog(self)
        if dlg.exec():
            self.servers.append(dlg.get_server())
            self.save_settings()
            self.refresh_table()

    def edit_server(self):
        srv = self.selected_server()
        if not srv:
            return
        dlg = ServerDialog(self, srv)
        if dlg.exec():
            dlg.get_server(srv)
            self.save_settings()
            self.refresh_table()

    def delete_server(self):
        srv = self.selected_server()
        if not srv:
            return
        if QMessageBox.question(self, T("delete_title"), f"«{srv.name}» {T('delete_q')}") \
                == QMessageBox.Yes:
            self.servers.remove(srv)
            self.last_results.pop(srv.id, None)
            self.save_settings()
            self.refresh_table()

    def import_servers(self):
        dlg = ImportDialog(self)
        if dlg.exec():
            new = dlg.get_servers()
            if new:
                self.servers.extend(new)
                self.save_settings()
                self.refresh_table()
                QMessageBox.information(self, T("import"), f"{len(new)} {T('import_n')}")
            else:
                QMessageBox.information(self, T("import"), T("import_none"))

    # -- تنظیمات -----------------------------------------------------------------
    def preview_theme(self, theme):
        """پیش‌نمایش لحظه‌ای تم از داخل دیالوگ تنظیمات."""
        apply_theme(theme)

    def open_settings(self):
        dlg = SettingsDialog(self, self.theme, self.auto_check_update)
        orig_theme = self.theme
        if dlg.exec():
            theme, auto = dlg.values()
            self.theme = theme
            self.auto_check_update = auto
            apply_theme(theme)
            self.save_settings()
        else:
            apply_theme(orig_theme)

    # -- آپدیت -------------------------------------------------------------------
    def check_for_updates(self, manual=False, status_label=None):
        def worker():
            try:
                rel = fetch_latest_release()
                newer = _ver_tuple(rel.get("tag_name", "0")) > _ver_tuple(__version__)
            except Exception as e:
                if manual:
                    msg = f"{T('update_err')} {e}"
                    if status_label:
                        QTimer.singleShot(0, lambda: status_label.setText(msg))
                    else:
                        QTimer.singleShot(0, lambda: QMessageBox.warning(
                            self, T("update"), msg))
                return
            if newer:
                QTimer.singleShot(0, lambda: self.update_found.emit(rel))
                if manual and status_label:
                    tag = rel.get("tag_name", "")
                    QTimer.singleShot(0, lambda: status_label.setText(
                        f"{T('new_version')} {tag} {T('update_avail')}"))
            elif manual:
                msg = T("update_latest")
                if status_label:
                    QTimer.singleShot(0, lambda: status_label.setText(msg))
                else:
                    QTimer.singleShot(0, lambda: QMessageBox.information(
                        self, T("update"), msg))
        threading.Thread(target=worker, daemon=True).start()

    @Slot(dict)
    def on_update_found(self, release):
        tag = release.get("tag_name", "")
        dlg = UpdateDialog(self, release)
        if dlg.exec() and dlg.choice:
            if dlg.choice == "setup":
                asset = find_setup_asset(release)
                kind = "setup"
            else:
                asset = find_portable_asset(release)
                kind = "portable"
            if not asset:
                QMessageBox.warning(self, T("update"), T("file_not_found"))
                return
            self.download_and_install(asset, tag, kind)

    def download_and_install(self, asset, tag, kind="setup"):
        url = asset.get("browser_download_url", "")
        name = asset.get("name", "StreamScanner-Setup.exe")
        if kind == "portable":
            dest = str(Path.home() / "Downloads" / f"StreamScanner-{tag}-Portable.exe")
        else:
            dest = str(Path(tempfile.gettempdir()) / name)
        prog = QProgressDialog(T("downloading"), T("cancel"), 0, 0, self)
        prog.setWindowModality(Qt.WindowModal)
        prog.show()

        def worker():
            try:
                req = urllib.request.Request(
                    url, headers={"User-Agent": "StreamScanner"})
                with urllib.request.urlopen(req, timeout=60) as r, \
                        open(dest, "wb") as f:
                    while True:
                        chunk = r.read(1024 * 256)
                        if not chunk:
                            break
                        f.write(chunk)
            except Exception as e:
                QTimer.singleShot(0, lambda: (prog.close(), QMessageBox.warning(
                    self, T("update"), f"{T('download_failed')}\n{e}")))
                return
            def done():
                prog.close()
                if kind == "portable":
                    QMessageBox.information(
                        self, T("update"), f"{T('portable_saved')}\n{dest}")
                    return
                if QMessageBox.question(
                        self, T("update"),
                        f"{T('version')} {tag} {T('downloaded')} {T('install_q')}") \
                        == QMessageBox.Yes:
                    try:
                        if sys.platform == "win32":
                            import os as _os
                            _os.startfile(dest)  # noqa
                        else:
                            QMessageBox.information(
                                self, T("update"), f"{T('installer_file')}\n{dest}")
                    finally:
                        QApplication.quit()
            QTimer.singleShot(0, done)
        threading.Thread(target=worker, daemon=True).start()


def _resource_base():
    """مسیر پایه فایل‌های باندل‌شده؛ سازگار با PyInstaller (onefile)."""
    _meipass = getattr(sys, "_MEIPASS", None)
    if _meipass:
        return Path(_meipass)
    return Path(__file__).resolve().parent


def _register_fonts():
    """ثبت فونت‌های Estedad باندل‌شده داخل برنامه (بدون نیاز به نصب روی ویندوز)."""
    try:
        fonts_dir = _resource_base() / "assets" / "fonts"
        for _fname in ("Estedad-Regular.ttf", "Estedad-Bold.ttf"):
            _fp = fonts_dir / _fname
            if _fp.is_file():
                QFontDatabase.addApplicationFont(str(_fp))
    except Exception:
        pass


def main():
    app = QApplication(sys.argv)
    app.setApplicationName(APP_NAME)
    app.setOrganizationName("StreamScanner")
    app.setWindowIcon(app_icon())
    app.setLayoutDirection(Qt.RightToLeft)
    _register_fonts()
    font = QFont("Estedad", 10)
    if "Estedad" not in QFont().families():
        font = QFont()
        font.setPointSize(10)
    app.setFont(font)
    win = MainWindow()
    win.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
